#!/bin/sh

APP=goglauncher

cd /opt/bin;
mkdir tmp;
cd ./tmp;
wget https://gitlab.com/Aztorius/GOGLauncher/-/jobs/75423350/artifacts/raw/GOGLauncher-x86_64.AppImage;
cd ..;
mv ./tmp/*mage ./$APP;
chmod a+x /opt/bin/$APP;

echo "[Desktop Entry]

Type=Application
Version=1.0
Name=GOGLauncher
Comment=GOG Games Launcher
Exec=/opt/bin/goglauncher
Icon=goglauncher
Terminal=false
Categories=Game;" >> /home/$USER/.local/share/applications/$APP.desktop;

wget https://raw.githubusercontent.com/ivan-hc/AppMan/main/applications/$APP/$APP.svg;
mv ./$APP.svg /home/$USER/.local/share/icons/;

echo "";
echo " GOGLauncher is provided by https://gitlab.com/Aztorius ";
echo "";

rm -R /opt/bin/tmp /opt/bin/$APP-installer
