#!/bin/sh

APP=sqlitebrowser

cd /opt/bin;
mkdir tmp;
cd ./tmp;
wget -r -A .AppImage -nd https://download.sqlitebrowser.org/;
cd ..;
mv ./tmp/*mage ./$APP;
chmod a+x /opt/bin/$APP;

echo "[Desktop Entry]
Name=DB Browser for SQLite
Comment=DB Browser for SQLite is a light GUI editor for SQLite databases
Comment[de]=DB Browser for SQLite ist ein GUI-Editor für SQLite-Datenbanken
Comment[fr]=Un éditeur graphique léger pour les bases de données SQLite
Comment[es]=«DB Browser for SQLite» es un editor gráfico de bases de datos SQLite
Exec=/opt/bin/sqlitebrowser %f
Icon=sqlitebrowser
Terminal=false
X-MultipleArgs=false
Type=Application
Categories=Development;Utility;Database;
MimeType=application/vnd.db4s-project+xml;application/sqlitebrowser;application/x-sqlitebrowser;application/vnd.sqlite3;application/geopackage+sqlite3;application/x-sqlite2;application/x-sqlite3;
X-AppImage-Version=v3.12.2" >> /home/$USER/.local/share/applications/$APP.desktop;

wget https://raw.githubusercontent.com/ivan-hc/AppMan/main/applications/$APP/$APP.svg;
mv ./$APP.svg /home/$USER/.local/share/icons/;

echo "";
echo " SQLite Browser is provided by https://sqlitebrowser.org ";
echo "";

rm -R /opt/bin/tmp /opt/bin/$APP-installer
