#!/bin/sh

cd /opt/bin;
wget https://dl.google.com/android/repository/platform-tools-latest-linux.zip;
rm -R ./platform-tools;
unzip ./platform-tools-latest-linux.zip;
rm ./platform-tools-latest-linux.zip;
ln -s /opt/bin/platform-tools/adb /opt/bin/adb;
ln -s /opt/bin/platform-tools/fastboot /opt/bin/fastboot;
echo "";
echo "  This is the complete Android-SDK Platform Tools suite";
echo "            including 'adb' and 'fastboot'";
echo "              'appman -i platform-tools' ";
echo "to install a new and more updated version, when available ";
echo "";
rm -R -f /opt/bin/*-installer
