#!/bin/sh

cd /opt/bin;
mkdir /home/$USER/.android;
cd ~/.android; wget https://dl.google.com/android/repository/platform-tools-latest-linux.zip;
rm -R ./platform-tools;
unzip ./platform-tools-latest-linux.zip;
rm ./platform-tools-latest-linux.zip;
ln -s /home/$USER/.android/platform-tools/adb /opt/bin/adb;
ln -s /home/$USER/.android/platform-tools/fastboot /opt/bin/fastboot;
echo "";
echo "   This is the complete Android-SDK Platform Tools suite";
echo "            'appremove adb && appinstall adb' ";
echo "to install a new and more updated version, when available ";
echo "";
rm /opt/bin/platform-tools-installer
