#!/bin/sh

APP=tag-editor

cd /opt/bin;
mkdir tmp;
cd ./tmp;
wget https://download.opensuse.org/repositories/home:/mkittler:/appimage/AppImage/tageditor-latest-x86_64.AppImage;
cd ..;
mv ./tmp/*mage ./$APP;
chmod a+x /opt/bin/$APP;

echo "[Desktop Entry]
Name=Tag Editor
GenericName=Tag Editor
Comment=A tageditor with Qt GUI and command line interface. Supports MP4 (iTunes), ID3, Vorbis, Opus, FLAC and Matroska
Exec=/opt/bin/tag-editor
Icon=tag-editor
Terminal=false
Type=Application
Categories=AudioVideo;" >> /home/$USER/.local/share/applications/$APP.desktop;

wget https://raw.githubusercontent.com/ivan-hc/AppMan/main/applications/$APP/$APP.svg;
mv ./$APP.svg /home/$USER/.local/share/icons/;

echo "";
echo "      Tag Editor AppImage is provided by LINK ";
echo "https://download.opensuse.org/repositories/home:/mkittler";
echo "";

rm -R /opt/bin/tmp /opt/bin/$APP-installer
