#!/bin/sh

APP=liketaskmanager

cd /opt/bin;
mkdir tmp;
cd ./tmp;
wget https://github.com/$(wget https://github.com/rejuce/LikeTaskManager/releases/latest -O - | egrep '/.*/.*/.*AppImage' -o);
cd ..;
mv ./tmp/*mage ./$APP;
chmod a+x /opt/bin/$APP;

rm /home/$USER/.local/share/applications/$APP.desktop;
echo "[Desktop Entry]
Type=Application
Name=LikeTaskManager
Comment=Tool that mimics the permformance monitoring of windows task manager under linux
Exec=/opt/bin/liketaskmanager
Icon=liketaskmanager
Categories=System;
Name[de_DE]=LikeTaskManager" >> /home/$USER/.local/share/applications/$APP.desktop;

wget https://raw.githubusercontent.com/ivan-hc/AppMan/main/applications/$APP/$APP.svg;
mv ./$APP.svg /home/$USER/.local/share/icons/;

echo "";
echo " LikeTaskManager is provided by https://github.com/rejuce ";
echo "";

rm -R /opt/bin/tmp /opt/bin/$APP-installer
