#!/bin/sh

cd /opt/bin;
mkdir tmp;
cd ./tmp;
wget -r -A .AppImage -nd https://github.com/srevinsaju/Firefox-AppImage/releases/tag/firefox;
cd ..;
mv ./tmp/firefox*AppImage ./firefox-stable;
chmod a+x /opt/bin/firefox-stable;
echo "[Desktop Entry]
Encoding=UTF-8
Version=1.0
Name=Firefox Stable
Comment=Web Browser
Exec=/opt/bin/firefox-stable %u
Terminal=false
Type=Application
Icon=firefox-stable
Categories=Network;WebBrowser;
MimeType=text/html;text/xml;application/xhtml+xml;application/xml;application/vnd.mozilla.xul+xml;application/rss+xml;application/rdf+xml;image/gif;image/jpeg;image/png;x-scheme-handler/http;x-scheme-handler/https;
StartupNotify=true
Path=;"  >> /home/$USER/.local/share/applications/firefox-stable.desktop;
wget https://raw.githubusercontent.com/ivan-hc/AppMan/main/applications/firefox/firefox-stable.svg;
mv ./firefox-stable.svg /home/$USER/.local/share/icons/;
echo "Visit https://github.com/srevinsaju";
rm -R /opt/bin/tmp /opt/bin/firefox-stable-installer
