#!/bin/sh

APP=ember

cd /opt/bin;
mkdir tmp;
cd ./tmp;
wget https://download.opensuse.org/repositories/games:/WorldForge/AppImage/ember-latest-x86_64.AppImage;
cd ..;
mv ./tmp/*mage ./$APP;
chmod a+x /opt/bin/$APP;

echo "[Desktop Entry]
Type=Application
Name=Ember
GenericName=3d client for Worldforge MMORPGs
GenericName[sv]=3d klient för Worldforge MMORPGs
GenericName[tr]=Worldforge MMORPG için 3B İstemci
Icon=ember
Exec=/opt/bin/ember
Terminal=false
Categories=Game;RolePlaying;
Keywords=Game;Role Playing;Role-Playing;3D;3-D;Massively;Multiplayer;Online;MMO;MMORPG;Fantasy;" >> /home/$USER/.local/share/applications/$APP.desktop;

wget https://raw.githubusercontent.com/ivan-hc/AppMan/main/applications/$APP/$APP.svg;
mv ./$APP.svg /home/$USER/.local/share/icons/;

echo "";
echo " Ember is provided by https://worldforge.gg ";
echo "";

rm -R /opt/bin/tmp /opt/bin/$APP-installer
