#!/bin/sh

cd /opt/bin;
mkdir tmp;
cd ./tmp;
wget -r -A .AppImage -nd https://github.com/srevinsaju/Firefox-AppImage/releases/tag/firefox-beta;
cd ..;
mv ./tmp/firefox*AppImage ./firefox-beta;
chmod a+x /opt/bin/firefox-beta;
echo "[Desktop Entry]
Encoding=UTF-8
Version=1.0
Name=Firefox Beta
Comment=Web Browser
Exec=/opt/bin/firefox-beta %u
Terminal=false
Type=Application
Icon=firefox-beta
Categories=Network;WebBrowser;
MimeType=text/html;text/xml;application/xhtml+xml;application/xml;application/vnd.mozilla.xul+xml;application/rss+xml;application/rdf+xml;image/gif;image/jpeg;image/png;x-scheme-handler/http;x-scheme-handler/https;
StartupNotify=true
Path=;"  >> /home/$USER/.local/share/applications/firefox-beta.desktop;
wget https://raw.githubusercontent.com/ivan-hc/AppMan/main/applications/firefox-beta/firefox-beta.svg;
mv ./firefox-beta.svg /home/$USER/.local/share/icons/;
echo "";
echo " Firefox AppImage is provided by https://github.com/srevinsaju ";
echo "";
rm -R /opt/bin/tmp /opt/bin/firefox-beta-installer
