#!/bin/sh

APP=groot

cd /opt/bin;
mkdir tmp;
cd ./tmp;
wget https://github.com/$(wget https://github.com/BehaviorTree/Groot/releases/latest -O - | egrep '/.*/.*/.*AppImage' -o);
cd ..;
mv ./tmp/*mage ./$APP;
chmod a+x /opt/bin/$APP;

rm /home/$USER/.local/share/applications/$APP.desktop;
echo "[Desktop Entry]
Name=Groot
Exec=/opt/bin/groot
Comment=Graphical Editor, written in C++ and Qt, to create BehaviorTrees.
Icon=groot
Type=Application
Categories=Utility;System;Office;Game;Network;Development;Education;AudioVideo;Graphics;" >> /home/$USER/.local/share/applications/$APP.desktop;

wget https://raw.githubusercontent.com/ivan-hc/AppMan/main/applications/$APP/$APP.svg;
mv ./$APP.svg /home/$USER/.local/share/icons/;

echo "";
echo " This AppImage is provided by https://github.com/BehaviorTree/Groot ";
echo "";

rm -R -f /opt/bin/tmp /opt/bin/$APP-installer /opt/bin/$APP-updater
