#!/bin/sh

APP=endless-sky

cd /opt/bin;
mkdir tmp;
cd ./tmp;

v=$(wget -q https://api.github.com/repos/endless-sky/endless-sky/releases/latest -O - | grep -E tag_name | awk -F '[""]' '{print $4}')
wget https://github.com/endless-sky/endless-sky/releases/download/$v/endless-sky-amd64-$v.AppImage;

cd ..;
mv ./tmp/*mage ./$APP;
chmod a+x /opt/bin/$APP;

rm /home/$USER/.local/share/applications/$APP.desktop;
echo "[Desktop Entry]
Name=Endless Sky
GenericName=Space game
GenericName[de]=Weltraumspiel
GenericName[fr]=Jeu spatial
Comment=Space exploration and combat game
Comment[de]=Weltraumhandels und Kampfsimulator
Comment[fr]=Jeu d'exploration et de combat dans l'espace
Exec=/opt/bin/endless-sky
Icon=endless-sky
Terminal=false
Type=Application
Keywords=game;simulator;space;sandbox;rpg;
Categories=Game;Simulation;" >> /home/$USER/.local/share/applications/$APP.desktop;

wget https://raw.githubusercontent.com/ivan-hc/AppMan/main/applications/$APP/$APP.svg;
mv ./$APP.svg /home/$USER/.local/share/icons/;

echo "";
echo " Endless Sky is provided by https://github.com/endless-sky";
echo "";

rm -R /opt/bin/tmp /opt/bin/$APP-installer
