#!/bin/sh

APP=telegram

cd /opt/bin;
mkdir tmp;
cd ./tmp;


pkg2appimage Telegram;


ARCH=x86_64 appimagetool -n ./Telegram/Telegram.AppDir;

cd ..;

mv /opt/bin/tmp/*AppImage /opt/bin/$APP; 
chmod a+x /opt/bin/$APP;

echo "[Desktop Entry]
Encoding=UTF-8
Version=1.0
Name=Telegram
Comment=Official desktop version of Telegram messaging app
Exec=/opt/bin/telegram -- %u
StartupWMClass=telegram-desktop
Icon=telegram
Terminal=false
Type=Application
Categories=Network;
MimeType=application/x-xdg-protocol-tg;x-scheme-handler/tg;
X-Desktop-File-Install-Version=0.22
X-AppImage-Version=3.0.1.glibc2.17" >> /home/$USER/.local/share/applications/$APP.desktop;


echo "";
echo "      This AppImage is provided by";
echo " https://github.com/AppImage/pkg2appimage ";
echo "";


wget https://raw.githubusercontent.com/ivan-hc/AppMan/main/applications/$APP/$APP.svg;
mv ./$APP.svg /home/$USER/.local/share/icons/;
rm -R /opt/bin/$APP-installer /opt/bin/tmp
