#!/bin/sh

APP=ksirk

cd /opt/bin;
mkdir tmp;
cd ./tmp;

echo "app: ksirk
binpatch: true

ingredients:
  dist: stable
  sources:
    - deb http://ftp.us.debian.org/debian/ stable main contrib non-free" >> recipe.yml

pkg2appimage ./recipe.yml;


ARCH=x86_64 appimagetool -n ./$APP/$APP.AppDir;

cd ..;

mv /opt/bin/tmp/*AppImage /opt/bin/$APP; 
chmod a+x /opt/bin/$APP;

rm /home/$USER/.local/share/applications/$APP.desktop;
echo "# KDE Config File
[Desktop Entry]
Type=Application
Exec=/opt/bin/ksirk -qwindowtitle %c -qwindowicon ksirk
Icon=ksirk
X-DocPath=ksirk/index.html
Terminal=false
Name=KsirK
Name[bs]=KsirK
Name[ca]=KsirK
Name[ca@valencia]=KsirK
Name[cs]=KsirK
Name[da]=KsirK
Name[de]=KsirK
Name[el]=KsirK
Name[en_GB]=KsirK
Name[es]=KsirK
Name[et]=KsirK
Name[eu]=KsirK
Name[fi]=KsirK
Name[fr]=KsirK
Name[ga]=KsirK
Name[gl]=KsirK
Name[hne]=केसिर्क
Name[hu]=KsirK
Name[it]=KsirK
Name[ja]=KsirK
Name[kk]=KsirK
Name[km]=KsirK
Name[ko]=KsirK
Name[lt]=KsirK
Name[lv]=KsirK
Name[mr]=के-सिर्क
Name[nb]=KSirK
Name[nds]=KsirK
Name[nl]=KsirK
Name[nn]=KsirK
Name[pl]=KsirK
Name[pt]=KsirK
Name[pt_BR]=KsirK
Name[ro]=KsirK
Name[ru]=KsirK
Name[sk]=KsirK
Name[sl]=KsirK
Name[sr]=К‑сирк
Name[sr@ijekavian]=К‑сирк
Name[sr@ijekavianlatin]=KSirk
Name[sr@latin]=KSirk
Name[sv]=Ksirk
Name[tr]=KsirK
Name[ug]=KsirK
Name[uk]=KsirK
Name[wa]=KsirK
Name[x-test]=xxKsirKxx
Name[zh_CN]=KsirK
Name[zh_TW]=KsirK
GenericName=World Domination Strategy Game
GenericName[bs]=Dominacija svijetom strategijska igra
GenericName[ca]=Joc d'estratègia per a la dominació mundial
GenericName[ca@valencia]=Joc d'estratègia per a la dominació mundial
GenericName[cs]=Strategická hra o světovou dominanci
GenericName[da]=Strategispil om verdensherredømmet
GenericName[de]=Welteroberungsspiel
GenericName[el]=Παιχνίδι στρατηγικής παγκόσμιας κυριαρχίας
GenericName[en_GB]=World Domination Strategy Game
GenericName[es]=Juego de estrategia de dominación mundial
GenericName[et]=Maailma vallutamise strateegiamäng
GenericName[eu]=Mudua menderatzeko estrategia jokoa
GenericName[fi]=Maailmanvalloituspeli
GenericName[fr]=Jeu de stratégie pour la conquête du monde
GenericName[ga]=Cluiche Fhorlámhas an Domhain
GenericName[gl]=Xogo de estratexia e dominación mundial
GenericName[hne]=वर्ल्ड डामिनेसन कौसल वाले खेल
GenericName[hu]=Világhódítós stratégiai játék
GenericName[it]=Gioco di strategia per la dominazione del mondo
GenericName[ja]=世界制覇ゲーム
GenericName[kk]=Әлем үстемдігі үшін стратегия ойны
GenericName[km]=ល្បែង​យុទ្ធសាស្ត្រ​គ្រប់គ្រង​ពិភពលោក​​
GenericName[ko]=우주 정복 전략 게임
GenericName[lv]=Pasaules pārvaldīšanas stratēģiskā spēle
GenericName[mr]=विश्व प्रभुत्व रणनीतिक खेळ
GenericName[nb]=Kamp om verdensherredømme
GenericName[nds]=Weltherrschop-Strategiespeel
GenericName[nl]=Werelddominatie-strategiespel
GenericName[nn]=Kamp om verdsherredøme
GenericName[pl]=Gra we władzę nad światem
GenericName[pt]=Jogo Estratégico de Conquista do Mundo
GenericName[pt_BR]=Jogo de estratégias de dominação do mundial
GenericName[ro]=Joc de strategie de dominație mondială
GenericName[ru]=Стратегическая игра в мировое господство
GenericName[sk]=Strategická hra s ovládnutím sveta
GenericName[sl]=Strateška igra osvajanja ozemlja
GenericName[sr]=Стратешка игра светске превласти
GenericName[sr@ijekavian]=Стратешка игра свјетске превласти
GenericName[sr@ijekavianlatin]=Strateška igra svjetske prevlasti
GenericName[sr@latin]=Strateška igra svetske prevlasti
GenericName[sv]=Strategispel för världsdominans
GenericName[tr]=Dünya Hakimiyeti Strateji Oyunu
GenericName[ug]=دۇنيا ھۆكۈمرانلىقى ئستراتېگىيە ئويۇنى
GenericName[uk]=Стратегічна гра у світове панування
GenericName[wa]=Djeu di stratedjeye pos esse li mwaisse do monde
GenericName[x-test]=xxWorld Domination Strategy Gamexx
GenericName[zh_CN]=世界支配战略游戏
GenericName[zh_TW]=征服世界戰略遊戲
Categories=Qt;KDE;Game;StrategyGame;
X-KDE-StartupNotify=true
X-DBUS-StartupType=Multi
X-DBUS-ServiceName=org.kde.ksirk" >> /home/$USER/.local/share/applications/$APP.desktop;

wget https://raw.githubusercontent.com/ivan-hc/AppMan/main/applications/$APP/$APP.svg;
mv ./$APP.svg /home/$USER/.local/share/icons/;

echo "";
echo "   This AppImage was created from Debian Stable using";
echo "";
echo "       https://github.com/AppImage/pkg2appimage ";
echo "";

rm -R -f /opt/bin/tmp /opt/bin/$APP-installer /opt/bin/$APP-updater
