#!/bin/sh

APP=baiji-manga-viewer

cd /opt/bin;
mkdir tmp;
cd ./tmp;
wget https://github.com/$(wget https://github.com/jmarioste/manga-viewer/releases/latest -O - | egrep '/.*/.*/.*AppImage' -o);
cd ..;
mv ./tmp/*mage ./$APP;
chmod a+x /opt/bin/$APP;

rm /home/$USER/.local/share/applications/$APP.desktop;
echo "[Desktop Entry]
Name=Baiji Manga Viewer
Exec=/opt/bin/baiji-manga-viewer
Comment=A modern manga viewer inspired by Quivi that uses Material Design
Icon=baiji-manga-viewer
Type=Application
Categories=Graphics;" >> /home/$USER/.local/share/applications/$APP.desktop;

wget https://raw.githubusercontent.com/ivan-hc/AppMan/main/applications/$APP/$APP.svg;
mv ./$APP.svg /home/$USER/.local/share/icons/;

echo "";
echo " Baiji is provided by https://github.com/jmarioste/manga-viewer ";
echo "";

rm -R -f /opt/bin/tmp /opt/bin/$APP-installer /opt/bin/$APP-updater
