#!/bin/sh

APP=klines

cd /opt/bin;
mkdir tmp;
cd ./tmp;

echo "app: klines
binpatch: true

ingredients:
  dist: stable
  sources:
    - deb http://ftp.us.debian.org/debian/ stable main contrib non-free" >> recipe.yml

pkg2appimage ./recipe.yml;


ARCH=x86_64 appimagetool -n ./$APP/$APP.AppDir;

cd ..;

mv /opt/bin/tmp/*AppImage /opt/bin/$APP; 
chmod a+x /opt/bin/$APP;

rm /home/$USER/.local/share/applications/$APP.desktop;
echo "# KDE Config File
[Desktop Entry]
Type=Application
Exec=/opt/bin/klines -qwindowtitle %c
Icon=klines
X-DocPath=klines/index.html
GenericName=Tactical Game
GenericName[af]=Taktiese Speletjie
GenericName[be]=Тактычная гульня
GenericName[bn]=কৌশলের খেলা
GenericName[br]=C'hoari a vrezelekaouriezh
GenericName[bs]=Taktična igra
GenericName[ca]=Joc de tàctica
GenericName[ca@valencia]=Joc de tàctica
GenericName[cs]=Taktická hra
GenericName[cy]=Gêm Dactegol
GenericName[da]=Taktisk spil
GenericName[de]=Kugeln entfernen
GenericName[el]=Παιχνίδι τακτικής
GenericName[en_GB]=Tactical Game
GenericName[eo]=Taktika ludo
GenericName[es]=Juego de táctica
GenericName[et]=Taktikamäng
GenericName[eu]=Joko taktikoa
GenericName[fa]=بازی برنامه‌ریزی‌شده
GenericName[fi]=Taktiikkapeli
GenericName[fr]=Jeu de tactique
GenericName[ga]=Cluiche Taicticiúil
GenericName[gl]=Xogo de táctica
GenericName[he]=משחק טקטי
GenericName[hne]=रननीतिक खेल
GenericName[hr]=Taktička igra
GenericName[hu]=Taktikai játék
GenericName[id]=Permainan Taktik
GenericName[is]=Herkænskuleikur
GenericName[it]=Gioco di tattica
GenericName[ja]=戦略的ゲーム
GenericName[kk]=Тактикалық ойын
GenericName[km]=ល្បែង​ក្បួន​យុទ្ធសាស្ត្រ
GenericName[ko]=전략 게임
GenericName[lt]=Taktinis žaidimas
GenericName[lv]=Taktiskā spēle
GenericName[mai]=रणनीतिक खेल
GenericName[mk]=Тактичка игра
GenericName[mr]=सामरिक खेळ
GenericName[nb]=Taktikk-spill
GenericName[nds]=Taktikspeel
GenericName[ne]=कौशल खेल
GenericName[nl]=Tactisch spel
GenericName[nn]=Taktisk spel
GenericName[pa]=ਟਾਕਟੀਕਲ ਖੇਡ
GenericName[pl]=Gra taktyczna
GenericName[pt]=Jogo de Estratégia
GenericName[pt_BR]=Jogo tático
GenericName[ro]=Un joc de tactică
GenericName[ru]=Тактическая игра
GenericName[se]=Taktihkkaspeallu
GenericName[sk]=Taktická hra
GenericName[sl]=Strateška igra
GenericName[sq]=Lojë Taktike
GenericName[sr]=Тактичка игра
GenericName[sr@ijekavian]=Тактичка игра
GenericName[sr@ijekavianlatin]=Taktička igra
GenericName[sr@latin]=Taktička igra
GenericName[sv]=Taktikspel
GenericName[ta]=தந்திரமான விளையாட்டு
GenericName[tg]=Бозии Тактикӣ
GenericName[tr]=Taktik Oyunu
GenericName[ug]=تاكتىكىلىق ئويۇن
GenericName[uk]=Тактична гра
GenericName[vi]=Trò chơi chiến thuật 
GenericName[wa]=Djeu di tactike
GenericName[xh]=Umdlalo onamaqhinga
GenericName[x-test]=xxTactical Gamexx
GenericName[zh_CN]=战术游戏
GenericName[zh_TW]=戰術遊戲
Terminal=false
Name=Kolor Lines
Name[af]=Kleur Lyne
Name[be]=Каляровыя лініі
Name[bn]=কালার লাইন্স
Name[br]=Linenn Kolor
Name[bs]=Linije u boji
Name[ca]=Kolor Lines
Name[ca@valencia]=Kolor Lines
Name[cs]=Kolor Lines
Name[cy]=Kolor Lines
Name[da]=Kolor Lines
Name[de]=Kolor Lines
Name[el]=Kolor Lines
Name[en_GB]=Kolor Lines
Name[eo]=Kolorlinioj
Name[es]=Kolor Lines
Name[et]=Kolor Lines
Name[eu]=Kolor Lines
Name[fa]=خطوط رنگی
Name[fi]=Kolor Lines
Name[fr]=Kolor Lines
Name[ga]=Kolor Lines
Name[gl]=Kolor Lines
Name[he]=Kolor Lines
Name[hne]=कलर लाइन्स
Name[hr]=KNiz u boji
Name[hu]=Színes vonalak
Name[id]=Kolor Lines
Name[is]=Kolor Lines
Name[it]=Kolor Lines
Name[ja]=Kolor Lines
Name[kk]=Kolor Lines
Name[km]=Kolor Lines
Name[ko]=Kolor Lines
Name[lt]=Kolor Lines
Name[lv]=Kolor Lines
Name[mk]=Kolor Lines
Name[mr]=कलर लाईन्स
Name[nb]=Klinjer
Name[nds]=Kolor Lines
Name[ne]=रङ रेखा
Name[nl]=Kolor Lines
Name[nn]=Fargelinjer
Name[pa]=ਰੰਗ ਖੇਡ
Name[pl]=Kolorowe linie
Name[pt]=Linhas Coloridas
Name[pt_BR]=Kolor Lines
Name[ro]=Linii colorate
Name[ru]=Kolor Lines
Name[se]=Kolor Lines
Name[sk]=Farebné čiary
Name[sl]=Kolor Lines
Name[sq]=Vija me Ngjyra
Name[sr]=Обојене линије
Name[sr@ijekavian]=Обојене линије
Name[sr@ijekavianlatin]=Obojene linije
Name[sr@latin]=Obojene linije
Name[sv]=Färglinjer
Name[ta]=வண்ணக்கோடுகள்
Name[tg]=Хатҳои Рангӣ
Name[tr]=Renkli Çizgiler
Name[ug]=Kolor Lines
Name[uk]=Кольорові лінії
Name[vi]=Kolor Lines
Name[wa]=Royes di coleur
Name[xh]=Iilayini zeKolor 
Name[x-test]=xxKolor Linesxx
Name[zh_CN]=Kolor Lines
Name[zh_TW]=Kolor Lines 彩色線條
Comment=Tactical game
Comment[ca]=Joc de tàctica
Comment[ca@valencia]=Joc de tàctica
Comment[cs]=Taktická hra
Comment[da]=Taktisk spil
Comment[de]=Taktikspiel
Comment[el]=Παιχνίδι τακτικής
Comment[en_GB]=Tactical game
Comment[es]=Juego de táctica
Comment[et]=Taktikamäng
Comment[fi]=Taktiikkapeli
Comment[fr]=Jeu de tactique
Comment[gl]=Xogo de táctica.
Comment[id]=Permainan taktik
Comment[it]=Gioco di tattica
Comment[ko]=전략 게임
Comment[nl]=Tactisch spel
Comment[nn]=Taktisk spel
Comment[pl]=Gra taktyczna
Comment[pt]=Jogo táctico
Comment[pt_BR]=Jogo tático
Comment[ru]=Тактическая игра
Comment[sk]=Taktická hra
Comment[sl]=Strateška igra
Comment[sr]=Тактичка игра
Comment[sr@ijekavian]=Тактичка игра
Comment[sr@ijekavianlatin]=Taktička igra
Comment[sr@latin]=Taktička igra
Comment[sv]=Taktikspel
Comment[tr]=Taktik oyunu
Comment[uk]=Тактична гра
Comment[x-test]=xxTactical gamexx
Comment[zh_CN]=战术游戏
Comment[zh_TW]=戰術遊戲
X-DBUS-StartupType=Multi
Categories=Qt;KDE;Game;StrategyGame;
X-DBUS-ServiceName=org.kde.klines" >> /home/$USER/.local/share/applications/$APP.desktop;

wget https://raw.githubusercontent.com/ivan-hc/AppMan/main/applications/$APP/$APP.svg;
mv ./$APP.svg /home/$USER/.local/share/icons/;

echo "";
echo "   This AppImage was created from Debian Stable using";
echo "";
echo "       https://github.com/AppImage/pkg2appimage ";
echo "";

rm -R -f /opt/bin/tmp /opt/bin/$APP-installer /opt/bin/$APP-updater
