#!/usr/bin/env bash

################################################################################
#
# 			THIS IS A TRANSITION SCRIPT!
#
# Since version 5, "AppMan" and "AM" have been meged to share the same code.
#
# See https://github.com/ivan-hc/AM-Application-Manager/blob/main/APP-MANAGER
#
# This is a transition script that will download and rename the script above.
#
# So to make it work like "AppMan", "APP-MANAGER" will be renamed to "appman".
# 
# You will be able to run "AppMan" from the first moment you run this script,
#
# so you won't notice the difference with the real "AppMan" script.
#
# The method used by this transition script is the same of the "-s" option.
#
# For bug reports and feature requests in "AppMan", keep use this repository.
#
# New commits for the "AppMan"/"AM" code will be listed at the following URL:
#
# https://github.com/ivan-hc/AM-Application-Manager/commits/main/APP-MANAGER
#
################################################################################

DIR="$( cd "$( dirname "$0" )" && pwd )"

case $2 in
	*)
		wget -q https://raw.githubusercontent.com/ivan-hc/AM-application-manager/main/APP-MANAGER -O $DIR/appman && chmod a+x $DIR/appman
		cd $DIR
		exec ./appman "$@";;
esac
