#!/bin/sh

sudo mkdir /opt/bin;
sudo chown $USER /opt/bin;
cd /opt/bin;
wget https://github.com/ivan-hc/AppMan/raw/main/appimage-tools/appimagetool;
wget https://github.com/ivan-hc/AppMan/raw/main/appimage-tools/appimageupdate;
wget https://github.com/ivan-hc/AppMan/raw/main/appimage-tools/pkg2appimage;
wget https://raw.githubusercontent.com/ivan-hc/AppMan/main/opt/bin/appman;
wget https://raw.githubusercontent.com/ivan-hc/AppMan/main/opt/bin/appman-bak;
chmod a+x /opt/bin/appimageupdate /opt/bin/appimagetool /opt/bin/pkg2appimage /opt/bin/appman /opt/bin/appman-bak;
sudo ln -s /opt/bin/appimageupdate /usr/bin/appimageupdate;
sudo ln -s /opt/bin/appimagetool /usr/bin/appimagetool;
sudo ln -s /opt/bin/pkg2appimage /usr/bin/pkg2appimage;
sudo chown $USER /opt/bin/*;
