#!/bin/sh

APP=arma3-unix-launcher

cd /opt/bin;
mkdir tmp;
cd ./tmp;
wget https://github.com/$(wget https://github.com/muttleyxd/arma3-unix-launcher/releases/latest -O - | egrep '/.*/.*/.*AppImage' -o);
cd ..;
mv ./tmp/*mage ./$APP;
chmod a+x /opt/bin/$APP;

rm /home/$USER/.local/share/applications/$APP.desktop;
echo "[Desktop Entry]
Name=ArmA 3 Unix Launcher
Exec=/opt/bin/arma3-unix-launcher
Comment=ArmA 3 Launcher for Linux
Icon=arma3-unix-launcher
Type=Application
Categories=Game;" >> /home/$USER/.local/share/applications/$APP.desktop;

wget https://raw.githubusercontent.com/ivan-hc/AppMan/main/applications/$APP/$APP.svg;
mv ./$APP.svg /home/$USER/.local/share/icons/;

echo "";
echo " ArmA 3 Unix Launcher is provided by https://github.com/muttleyxd ";
echo "";

rm -R -f /opt/bin/tmp /opt/bin/$APP-installer /opt/bin/$APP-updater
