#!/bin/sh

APP=whatsapp-for-linux

cd /opt/bin;
mkdir tmp;
cd ./tmp;


wget https://github.com/$(wget https://github.com/eneshecan/whatsapp-for-linux/releases/latest -O - | egrep '/.*/.*/.*deb' -o);
ar x ./*.deb;
tar xf ./data.tar.xz;
mkdir $APP.AppDir;
mv ./usr ./$APP.AppDir;
cp ./$APP.AppDir/usr/share/applications/*.desktop ./$APP.AppDir;
cp ./$APP.AppDir/usr/share/icons/hicolor/128x128/apps/*.png ./$APP.AppDir;

echo '#!/bin/sh

HERE="$(dirname "$(readlink -f "${0}")")"
export PATH="${HERE}/usr/bin/:${HERE}/usr/share/${PATH:+:$PATH}"
export XDG_DATA_DIRS="${HERE}/usr/share/${XDG_DATA_DIRS:+:$XDG_DATA_DIRS}"
EXEC="${HERE}/usr/bin/whatsapp-for-linux"
exec "${EXEC}"' >> /opt/bin/tmp/$APP.AppDir/AppRun;
chmod a+x /opt/bin/tmp/$APP.AppDir/AppRun;

ARCH=x86_64 appimagetool -n ./$APP.AppDir;

cd ..;

mv /opt/bin/tmp/*AppImage /opt/bin/$APP; 
chmod a+x /opt/bin/$APP;
rm 
echo "[Desktop Entry]
Type=Application
Encoding=UTF-8
Version=1.0
Name=WhatsApp for Linux
GenericName=Unofficial WhatsApp client
Comment=An unofficial WhatsApp desktop application for linux
Exec=/opt/bin/whatsapp-for-linux
Icon=whatsapp-for-linux
Categories=GTK;GNOME;Network;
Keywords=chat;im;messaging;messenger;sms;whatsapp;whatsapp-desktop;" >> /home/$USER/.local/share/applications/$APP.desktop;


wget https://raw.githubusercontent.com/ivan-hc/AppMan/main/applications/$APP/$APP.svg;
mv ./$APP.svg /home/$USER/.local/share/icons/;
echo "";

echo "       This version of whatsapp-for-linux comes from";
echo "      https://github.com/eneshecan/whatsapp-for-linux";
echo "                'appman -i whatsapp-for-linux' ";
echo " to install a new and more updated version, when available ";

echo "";
rm -R /opt/bin/$APP-installer /opt/bin/tmp
