#!/bin/sh

APP=gdevelop

cd /opt/bin;
mkdir tmp;
cd ./tmp;

wget https://github.com/$(wget https://github.com/4ian/GDevelop/releases/latest -O - | egrep '/.*/.*/.*AppImage' -o)

cd ..;
mv ./tmp/*mage ./$APP;
chmod a+x /opt/bin/$APP;


rm /home/$USER/.local/share/applications/$APP.desktop;

echo "[Desktop Entry]
Name=GDevelop
Exec=/opt/bin/gdevelop
Comment=GDevelop game engine
Icon=gdevelop
Type=Application
Categories=Development;" >> /home/$USER/.local/share/applications/$APP.desktop;

wget https://raw.githubusercontent.com/ivan-hc/AppMan/main/applications/$APP/$APP.svg;
mv ./$APP.svg /home/$USER/.local/share/icons/;

echo "";
echo " This AppImage is provided by";
echo " https://github.com/4ian/GDevelop/ ";
echo "";

rm -R -f /opt/bin/tmp /opt/bin/$APP-installer /opt/bin/$APP-updater
