#!/bin/sh

APP=ardm

cd /opt/bin;
mkdir tmp;
cd ./tmp;
wget https://github.com/$(wget https://github.com/qishibo/AnotherRedisDesktopManager/releases/latest -O - | egrep '/.*/.*/.*AppImage' -o);
cd ..;
mv ./tmp/*mage ./$APP;
chmod a+x /opt/bin/$APP;

rm /home/$USER/.local/share/applications/$APP.desktop;
echo "[Desktop Entry]
Name=Another Redis Desktop Manager
Exec=/opt/bin/ardm --no-sandbox %U
Terminal=false
Type=Application
Icon=ardm
StartupWMClass=Another Redis Desktop Manager
Comment=A faster, better and more stable redis desktop manager.
Categories=Utility;" >> /home/$USER/.local/share/applications/$APP.desktop;

wget https://raw.githubusercontent.com/ivan-hc/AppMan/main/applications/$APP/$APP.svg;
mv ./$APP.svg /home/$USER/.local/share/icons/;

echo "";
echo "      AnotherRedisDesktopManager is provided by"
echo "";
echo " https://github.com/qishibo/AnotherRedisDesktopManager ";
echo "";

rm -R /opt/bin/tmp /opt/bin/$APP-installer
