#!/bin/sh

APP=vscodium

cd /opt/bin;
mkdir tmp;
cd ./tmp;
wget -r -A .AppImage -nd https://github.com/VSCodium/vscodium/releases/tag/1.59.1;
cd ..;
mv ./tmp/*mage ./$APP;
chmod a+x /opt/bin/$APP;

echo "[Desktop Entry]
Name=VSCodium
Comment=Code Editing. Redefined.
GenericName=Text Editor
Exec=/opt/bin/vscodium --unity-launch %F
Icon=vscodium
Type=Application
StartupNotify=false
StartupWMClass=VSCodium
Categories=Utility;TextEditor;Development;IDE;
MimeType=text/plain;inode/directory;application/x-codium-workspace;
Actions=new-empty-window;
Keywords=vscode;

X-AppImage-Version=1.59.1-1629418630.glibc2.17

[Desktop Action new-empty-window]
Name=New Empty Window
Exec=/opt/bin/vscodium --new-window %F
Icon=vscodium" >> /home/$USER/.local/share/applications/$APP.desktop;

wget https://raw.githubusercontent.com/ivan-hc/AppMan/main/applications/$APP/$APP.svg;
mv ./$APP.svg /home/$USER/.local/share/icons/;

echo "";
echo " VSCodium is provided by https://vscodium.com ";
echo "";

rm -R /opt/bin/tmp /opt/bin/$APP-installer
