#!/bin/sh

APP=poddr

cd /opt/bin;
mkdir tmp;
cd ./tmp;

v=$(wget -q https://api.github.com/repos/Sn8z/Poddr/releases/latest -O - | grep -E tag_name | awk -F '[""]' '{print $4}')
wget https://github.com/Sn8z/Poddr/releases/download/$v/Poddr-$v.AppImage;

cd ..;
mv ./tmp/*mage ./$APP;
chmod a+x /opt/bin/$APP;

rm /home/$USER/.local/share/applications/$APP.desktop;
echo "[Desktop Entry]
Name=Poddr
Exec=/opt/bin/poddr
Terminal=false
Type=Application
Icon=poddr
StartupWMClass=Poddr
Comment=Podcast client
Categories=Audio;Music;Player;AudioVideo;" >> /home/$USER/.local/share/applications/$APP.desktop;

wget https://raw.githubusercontent.com/ivan-hc/AppMan/main/applications/$APP/$APP.svg;
mv ./$APP.svg /home/$USER/.local/share/icons/;

echo "";
echo " Poddr Podcast Client is provided by https://github.com/Sn8z/Poddr";
echo "";

rm -R -f /opt/bin/tmp /opt/bin/$APP-installer /opt/bin/$APP-updater
