#!/bin/sh

APP=kpat

cd /opt/bin;
mkdir tmp;
cd ./tmp;

echo "app: kpat
binpatch: true

ingredients:
  dist: stable
  sources:
    - deb http://ftp.us.debian.org/debian/ stable main contrib non-free" >> recipe.yml

pkg2appimage ./recipe.yml;


ARCH=x86_64 appimagetool -n ./$APP/$APP.AppDir;

cd ..;

mv /opt/bin/tmp/*AppImage /opt/bin/$APP; 
chmod a+x /opt/bin/$APP;

rm /home/$USER/.local/share/applications/$APP.desktop;
echo "[Desktop Entry]
Name=KPatience
Name[bs]=KPatience
Name[ca]=KPatience
Name[ca@valencia]=KPatience
Name[cs]=KPatience
Name[da]=KPatience
Name[de]=KPatience
Name[el]=KPatience
Name[en_GB]=KPatience
Name[es]=KPatience
Name[et]=KPatience
Name[eu]=KPatience
Name[fi]=KPatience
Name[fr]=KPatience
Name[ga]=KPatience
Name[gl]=KPatience
Name[hne]=के-पेसेन्स
Name[hu]=KPatience
Name[id]=KPatience
Name[it]=KPatience
Name[ja]=KPatience
Name[kk]=KPatience
Name[km]=KPatience
Name[ko]=KPatience
Name[lt]=KPatience
Name[lv]=KPatience
Name[mr]=के-पेशन्स
Name[nb]=Kabal
Name[nds]=KPatience
Name[nl]=KPatience
Name[nn]=KPatience
Name[pa]=ਕੇਪੇਟੀਨਸ਼
Name[pl]=Pasjans
Name[pt]=KPatience
Name[pt_BR]=KPatience
Name[ro]=KPasențe
Name[ru]=KPatience
Name[sk]=KPatience
Name[sl]=KPatience
Name[sr]=К‑пасијанс
Name[sr@ijekavian]=К‑пасијанс
Name[sr@ijekavianlatin]=K‑pasijans
Name[sr@latin]=K‑pasijans
Name[sv]=Patiens
Name[tr]=KPatience
Name[ug]=KPatience
Name[uk]=Пасьянс
Name[wa]=KPacyince
Name[x-test]=xxKPatiencexx
Name[zh_CN]=KPatience
Name[zh_TW]=KPatience 單人紙牌遊戲
Exec=/opt/bin/kpat -qwindowtitle %c %u
Type=Application
Icon=kpat
X-DocPath=kpat/index.html
GenericName=Patience Card Game
GenericName[af]=Patience Kaart Speletjie
GenericName[be]=Картачны пасьянс
GenericName[bn]=পেশেন্স নামের তাস খেলা
GenericName[br]=C'hoari a habaskter
GenericName[bs]=Kartaška igra strpljenja
GenericName[ca]=Partida de cartes paciència
GenericName[ca@valencia]=Partida de cartes paciència
GenericName[cs]=Karetní hra passiáns
GenericName[cy]=Gêm Cerdiau Patience
GenericName[da]=Kabale-kortspil
GenericName[de]=Patiencen legen
GenericName[el]=Παιχνίδι καρτών πασιέντζας
GenericName[en_GB]=Patience Card Game
GenericName[eo]=Pacienca Kartludo
GenericName[es]=Juego de cartas Patience
GenericName[et]=Kaardimäng
GenericName[eu]=Pazientziako karta-jokoa
GenericName[fa]=بازی Patience Card
GenericName[fi]=Pasianssi-korttipeli
GenericName[fr]=Jeux de réussite
GenericName[ga]=Cluiche Cártaí Patience
GenericName[gl]=Xogo de cartas
GenericName[he]=משחק קלפים
GenericName[hne]=पेसेंस तास वाले खेल
GenericName[hr]=Kartaška igra pasijansa
GenericName[hu]=Pasziánsz kártyajáték
GenericName[id]=Permainan Kartu Patience
GenericName[is]=Kaplar
GenericName[it]=Solitari con le carte
GenericName[ja]=Patience カードゲーム
GenericName[kk]=Пасьянс ойны
GenericName[km]=ល្បែង​បៀ Patience
GenericName[ko]=카드 놀이
GenericName[lt]=Pasianso kortų žaidimas
GenericName[lv]=Patience kāršu spēle
GenericName[mk]=Пасијанс - игра со карти
GenericName[mr]=पेशन्स पत्यांचा खेळ
GenericName[nb]=Kabalspill
GenericName[nds]=Patschangsen leggen
GenericName[ne]=शान्त कार्ड खेल
GenericName[nl]=Patience-kaartspel
GenericName[nn]=Kabalspel
GenericName[pl]=Gra karciana Patience
GenericName[pt]=Jogo de Paciência
GenericName[pt_BR]=Jogo de cartas paciência
GenericName[ro]=Joc de cărți de răbdare
GenericName[ru]=Карточный пасьянс
GenericName[se]=Kabálaspeallu
GenericName[sk]=Kartová hra Patience
GenericName[sl]=Igra s kartami Patience
GenericName[sr]=Пасијанс са картама
GenericName[sr@ijekavian]=Пасијанс са картама
GenericName[sr@ijekavianlatin]=Pasijans sa kartama
GenericName[sr@latin]=Pasijans sa kartama
GenericName[sv]=Patienskortspel
GenericName[ta]=பொறுமையான சீட்டு விளையாட்டு
GenericName[te]=సహనం పేక ఆట
GenericName[tg]=Бозии Пасянси Кортӣ
GenericName[tr]=Sabır Kart Oyunu
GenericName[ug]=سەۋر تاقەت كارتا ئويۇنى
GenericName[uk]=Гра картами у пасьянс
GenericName[wa]=Cwårdjeu d' pacyince
GenericName[xh]=Ikhadi lomdlalo wokunyamezela
GenericName[x-test]=xxPatience Card Gamexx
GenericName[zh_CN]=考验耐心的牌类游戏
GenericName[zh_TW]=單人玩的紙牌遊戲
Comment=Solitaire card game
Comment[ca]=Joc de cartes al solitari
Comment[ca@valencia]=Joc de cartes al solitari
Comment[cs]=Karetní hra Solitaire
Comment[da]=Kabale kortspil
Comment[de]=Solitär-Kartenspiel
Comment[el]=Παιχνίδι καρτών solitaire
Comment[en_GB]=Solitaire card game
Comment[es]=Juego de cartas solitario
Comment[et]=Solitaire kaardimäng
Comment[eu]=Bakarkako karta-jokoa
Comment[fi]=Pasianssikorttipeli
Comment[fr]=Jeu de solitaire
Comment[gl]=Xogo de cartas do solitario.
Comment[id]=Permainan kartu solitaire
Comment[it]=Solitari con le carte
Comment[ko]=솔리테어 카드 게임
Comment[nl]=Solitaire kaartspel
Comment[nn]=Kabelspel
Comment[pl]=Gra pasjans
Comment[pt]=Jogo de cartas solitário
Comment[pt_BR]=Jogo de cartas paciência
Comment[sk]=Solitaire kartová hra
Comment[sl]=Igra Pasjanse
Comment[sr]=Игра пасијанса
Comment[sr@ijekavian]=Игра пасијанса
Comment[sr@ijekavianlatin]=Igra pasijansa
Comment[sr@latin]=Igra pasijansa
Comment[sv]=Patienskortspel
Comment[tr]=Solitaire kart oyunu
Comment[uk]=Карткова гра у пасьянс
Comment[x-test]=xxSolitaire card gamexx
Comment[zh_CN]=纸牌游戏
Comment[zh_TW]=接龍卡片遊戲
X-DBUS-StartupType=Multi
Categories=Qt;KDE;Game;CardGame;
MimeType=application/vnd.kde.kpatience.savedstate;
X-DBUS-ServiceName=org.kde.kpat" >> /home/$USER/.local/share/applications/$APP.desktop;

wget https://raw.githubusercontent.com/ivan-hc/AppMan/main/applications/$APP/$APP.svg;
mv ./$APP.svg /home/$USER/.local/share/icons/;

echo "";
echo "   This AppImage was created from Debian Stable using";
echo "";
echo "       https://github.com/AppImage/pkg2appimage ";
echo "";

rm -R -f /opt/bin/tmp /opt/bin/$APP-installer /opt/bin/$APP-updater
