#!/bin/sh

APP=arcade-manager

cd /opt/bin;
mkdir tmp;
cd ./tmp;
wget https://github.com/$(wget https://github.com/cosmo0/arcade-manager/releases/latest -O - | egrep '/.*/.*/.*AppImage' -o);
cd ..;
mv ./tmp/*mage ./$APP;
chmod a+x /opt/bin/$APP;

rm /home/$USER/.local/share/applications/$APP.desktop;
echo "[Desktop Entry]
Name=ArcadeManager
Exec=/opt/bin/arcade-manager --no-sandbox %U
Terminal=false
Type=Application
Icon=arcade-manager
StartupWMClass=ArcadeManager
X-AppImage-Version=5.1.0
Comment=Arcade games manager to be used with Retropie and Recalbox
Categories=Game;" >> /home/$USER/.local/share/applications/$APP.desktop;

wget https://raw.githubusercontent.com/ivan-hc/AppMan/main/applications/$APP/$APP.svg;
mv ./$APP.svg /home/$USER/.local/share/icons/;

echo "";
echo " ArcadeManager is provided by https://github.com/cosmo0 ";
echo "";

rm -R /opt/bin/tmp /opt/bin/$APP-installer
