#!/bin/sh

# $APP must use lowercase letters, because it is a "command".
# The same name is used for the icon SAMPLE.svg and the file about-SAMPLE in the main folder of the app.
APP=SAMPLE

# Entering in /opt/bin will be created a /tmp folder in which all the operations will be performed
cd /opt/bin;
mkdir tmp;
cd ./tmp;

# DIRECT DOWNLOADING the AppImage using wget, replace URL with the link of your app
# Or use a custom command to get always the last version 
wget URL;
# EXAMPLES:
# 1) To get the last version I use:
# wget https://github.com/$(wget https://github.com/USER/REPOSITORY/releases/latest -O - | egrep '/.*/.*/.*AppImage' -o)
# 2) To get a speciphic file from a list I use:
# wget -r -erobots=off -l1 -np -A APPNAME-*-EXTENSION -nd LINK
# 3) If on GitHub the version in the link is the same in the name of the file, I use two lines:
# v=$(wget -q https://api.github.com/repos/USER/REPOSITORY/releases/latest -O - | grep -E tag_name | awk -F '[""]' '{print $4}')
# wget https://github.com/USER/REPOSITORY/releases/download/$v/SAMPLE-$v-x86_64.AppImage
# There are several ways to use "wget", go to https://www.gnu.org/software/wget/ for more info.

# Renaming the downloaded AppImage to $APP
cd ..;
mv ./tmp/*mage ./$APP;
chmod a+x /opt/bin/$APP;


# Creating a LAUNCHER (the old one will be removed if already exists)
rm /home/$USER/.local/share/applications/$APP.desktop;
# This is an example of launcher:
# 1) APPNAME can be different from $APP with Capital letters if needed
# 2) $APP in Exec must be always placed in /opt/bin
# 3) COMMENT is the description of the app (optional)
# 4) Choose a category at the end to show the app into a category of the menu
echo "[Desktop Entry]
Name=APPNAME
Exec=/opt/bin/SAMPLE 
Comment=COMMENT
Icon=SAMPLE
Type=Application
Categories=Utility;System;Office;Game;Network;Development;Education;AudioVideo;Graphics;" >> /home/$USER/.local/share/applications/$APP.desktop;

# The icon of the app will be downloaded from this repository
wget https://raw.githubusercontent.com/ivan-hc/AppMan/main/applications/$APP/$APP.svg;
mv ./$APP.svg /home/$USER/.local/share/icons/;

# Replace LINK with the source of this app
echo "";
echo " This AppImage is provided by LINK ";
echo "";

# The installer script, the /tmp folder and an eventual "updater" file will be removed
rm -R -f /opt/bin/tmp /opt/bin/$APP-installer /opt/bin/$APP-updater
