#!/bin/sh

cd /opt/bin;
mkdir tmp;
cd tmp;
wget https://download.opensuse.org/repositories/home:/munix9:/unstable/AppImage/celestia-latest-x86_64.AppImage;
cd ..;
mv ./tmp/celestia*AppImage ./celestia-dev;
chmod a+x ./celestia-dev;

echo "[Desktop Entry]
Version=1.0
Name=Celestia Development Edition (GTK)
GenericName=Space Simulator (Unstable version)
Comment=Explore the Universe in this detailed space simulation
Comment[de]=Erkunde das Universum in dieser detaillierten Weltraumsimulation
Type=Application
Categories=Astronomy;Education;Science;GTK;
Icon=celestia-dev
Exec=/opt/bin/celestia-dev %f
Terminal=false
MimeType=application/x-celestia-script;" >> /home/$USER/.local/share/applications/celestia-dev.desktop;
wget wget https://raw.githubusercontent.com/ivan-hc/AppMan/main/applications/celestia/celestia.svg;
mv ./celestia.svg /home/$USER/.local/share/icons/celestia-dev.svg;

echo "";
echo "           Celestia is provided by https://celestia.space";
echo "";
echo " AppImage at https://download.opensuse.org/repositories/home:/munix9/AppImage";
echo "";

rm -R /opt/bin/tmp /opt/bin/celestia-dev-installer
