#!/bin/sh

APP=antares

cd /opt/bin;
mkdir tmp;
cd ./tmp;
wget https://github.com/$(wget https://github.com/Fabio286/antares/releases/latest -O - | egrep '/.*/.*/.*x86_64.AppImage' -o);
cd ..;
mv ./tmp/*mage ./$APP;
chmod a+x /opt/bin/$APP;

rm /home/$USER/.local/share/applications/$APP.desktop;
echo "[Desktop Entry]
Name=Antares
Exec=/opt/bin/antares --no-sandbox %U
Terminal=false
Type=Application
Icon=antares
StartupWMClass=Antares
Comment=A cross-platform easy to use SQL client.
Categories=Development;" >> /home/$USER/.local/share/applications/$APP.desktop;

wget https://raw.githubusercontent.com/ivan-hc/AppMan/main/applications/$APP/$APP.svg;
mv ./$APP.svg /home/$USER/.local/share/icons/;

echo "";
echo " Antares is provided by https://github.com/Fabio286 ";
echo "";

rm -R /opt/bin/tmp /opt/bin/$APP-installer
