#!/bin/sh

APP=gamehub

cd /opt/bin;
mkdir tmp;
cd ./tmp;
wget https://github.com/$(wget https://github.com/tkashkin/GameHub/releases/latest -O - | egrep '/.*/.*/.*AppImage' -o);
cd ..;
mv ./tmp/*mage ./$APP;
chmod a+x /opt/bin/$APP;

rm /home/$USER/.local/share/applications/$APP.desktop;
echo "[Desktop Entry]
Name=GameHub
GenericName=GameHub
Comment[ru]=Все игры в одном месте
Comment[pt_BR]=Todos os seus jogos em um só lugar
Comment[pt_PT]=Todos os seus jogos num só lugar
Comment[id]=Semua permainan Anda di satu tempat
Comment[nb_NO]=Alle dine spill på ett sted
Comment[nl]=Al je spellen op één plek
Comment[de]=Alle Ihre Spiele an einem Ort
Comment[fr]=Tous vos jeux en un endroit
Comment[pl]=Wszystkie twoje gry w jednym miejscu
Comment[tr]=Tüm oyunlarınızı tek bir yerde
Comment[fa]=همه بازی های شما در یک مکان
Comment[ar]=كل ألعابك في مكان واحد
Comment[ca]=Tots els teus jocs en un lloc
Comment[fi]=Kaikki pelisi yhdessä paikassa
Comment[es_MX]=Todos tus juegos en un solo lugar
Comment[it]=Tutti i tuoi giochi in un unico posto
Comment[zh_CN]=将您所有的游戏都整合到同一个地方
Comment[hr]=Sve vaše igre na jednom mjestu
Comment[es]=Todos sus juegos en un solo lugar
Comment[pt]=Todos os seus jogos num só lugar
Comment[eo]=Ĉiuj viaj ludoj en unu loko
Comment[sv]=Alla dina spel på ett ställe
Comment=All your games in one place
Categories=Game;Amusement;
Keywords=Game;Hub;Steam;GOG;Humble;HumbleBundle;
Exec=/opt/bin/gamehub
X-GNOME-Gettext-Domain=com.github.tkashkin.gamehub
Icon=gamehub
Terminal=false
Type=Application" >> /home/$USER/.local/share/applications/$APP.desktop;

wget https://raw.githubusercontent.com/ivan-hc/AppMan/main/applications/$APP/$APP.svg;
mv ./$APP.svg /home/$USER/.local/share/icons/;

echo "";
echo " GameHub is provided by https://tkashkin.tk ";
echo "";

rm -R -f /opt/bin/tmp /opt/bin/$APP-installer /opt/bin/$APP-updater
