#!/bin/sh

APP=linuxdeployqt

cd /opt/bin;
mkdir tmp;
cd ./tmp;
wget https://github.com/probonopd/linuxdeployqt/releases/download/continuous/linuxdeployqt-continuous-x86_64.AppImage;
cd ..;
mv ./tmp/*mage ./$APP;
chmod a+x /opt/bin/$APP;

echo "";
echo " LinuxDeployQT is provided by https://github.com/probonopd/linuxdeployqt ";
echo "";

rm -R /opt/bin/tmp /opt/bin/$APP-installer
