#!/bin/sh

APP=play-2048

cd /opt/bin;
mkdir tmp;
cd ./tmp;
wget https://github.com/mgrojo/play_2048/releases/download/continuous/Play_2048-main-x86_64.AppImage;
cd ..;
mv ./tmp/*mage ./$APP;
chmod a+x /opt/bin/$APP;

rm /home/$USER/.local/share/applications/$APP.desktop;
echo "[Desktop Entry]
Name=Play 2048
Exec=/opt/bin/play-2048
Comment=Another 2048 game
Icon=play-2048
Type=Application
Categories=Game;" >> /home/$USER/.local/share/applications/$APP.desktop;

wget https://raw.githubusercontent.com/ivan-hc/AppMan/main/applications/$APP/$APP.svg;
mv ./$APP.svg /home/$USER/.local/share/icons/;

echo "";
echo " Play 2048 is provided by https://github.com/mgrojo ";
echo "";

rm -R -f /opt/bin/tmp /opt/bin/$APP-installer /opt/bin/$APP-updater
