#!/bin/sh

APP=discord

cd /opt/bin;
mkdir tmp;
cd ./tmp;
wget -r -A .AppImage -nd https://github.com/srevinsaju/discord-appimage/releases/tag/stable;
cd ..;
mv ./tmp/*mage ./$APP;
chmod a+x /opt/bin/$APP;

echo "[Desktop Entry]
Name=Discord
StartupWMClass=discord
Comment=All-in-one voice and text chat for gamers that's free, secure, and works on both your desktop and phone.
GenericName=Internet Messenger
Exec=/opt/bin/discord
Icon=discord
Type=Application
Categories=Network;InstantMessaging;" >> /home/$USER/.local/share/applications/$APP.desktop;

wget https://raw.githubusercontent.com/ivan-hc/AppMan/main/applications/$APP/$APP.svg;
mv ./$APP.svg /home/$USER/.local/share/icons/;

echo "";
echo " Discord AppImage is provided by https://github.com/srevinsaju ";
echo "";

rm -R /opt/bin/tmp /opt/bin/$APP-installer
