#!/bin/sh

APP=mandelbulber2

cd /opt/bin;
mkdir tmp;
cd ./tmp;
wget https://github.com/$(wget https://github.com/buddhi1980/mandelbulber2/releases/latest -O - | egrep '/.*/.*/.*x86_64.appimage' -o);
cd ..;
mv ./tmp/*mage ./$APP;
chmod a+x /opt/bin/$APP;

rm /home/$USER/.local/share/applications/$APP.desktop;
echo "[Desktop Entry]
Name=mandelbulber2
Exec=/opt/bin/mandelbulber2
Comment=Explore trigonometric, hyper-complex, Mandelbox, IFS, and many other 3D fractals.
Icon=mandelbulber2
Type=Application
Categories=Graphics;" >> /home/$USER/.local/share/applications/$APP.desktop;

wget https://raw.githubusercontent.com/ivan-hc/AppMan/main/applications/$APP/$APP.svg;
mv ./$APP.svg /home/$USER/.local/share/icons/;

echo "";
echo " This AppImage is provided by https://github.com/buddhi1980/mandelbulber2 ";
echo "";

rm -R -f /opt/bin/tmp /opt/bin/$APP-installer /opt/bin/$APP-updater
