#!/bin/sh

cd /opt/bin;
mkdir tmp;
cd ./tmp;
wget https://github.com/spooknik/Photopea-Appimage/releases/download/1.2.1/Photopea_1.2.1_x86_64.AppImage;
cd ..;
mv ./tmp/photopea*AppImage ./photopea;
chmod a+x /opt/bin/photopea;

echo "[Desktop Entry]
Name=Photopea
Comment=Photopea in AppImage
Exec=AppRun
Terminal=false
Type=Application
Icon=photopea
StartupWMClass=Photopea
X-AppImage-Version=1.2.0
Categories=Graphics;
X-AppImage-BuildId=1JjD14uwyf7zD0MXVDkhft0XRpx" >> /home/$USER/.local/share/applications/photopea.desktop;

wget https://raw.githubusercontent.com/ivan-hc/AppMan/main/applications/photopea/photopea.svg;
mv ./photopea.svg /home/$USER/.local/share/icons/;

echo "";
echo " Photopea is provided by https://github.com/spooknik ";
echo "";

rm -R /opt/bin/tmp /opt/bin/photopea-installer
