#!/bin/sh

APP=musicalypse

cd /opt/bin;
mkdir tmp;
cd ./tmp;
wget https://github.com/$(wget https://github.com/tgambet/musicalypse/releases/latest -O - | egrep '/.*/.*/.*x64.AppImage' -o);
cd ..;
mv ./tmp/*mage ./$APP;
chmod a+x /opt/bin/$APP;

rm /home/$USER/.local/share/applications/$APP.desktop;
echo "[Desktop Entry]
Name=Musicalypse
Comment=A modern audio player built with Web technologies.
Exec=/opt/bin/musicalypse
Terminal=false
Type=Application
Icon=musicalypse
StartupWMClass=Musicalypse
Categories=AudioVideo;Audio;" >> /home/$USER/.local/share/applications/$APP.desktop;

wget https://raw.githubusercontent.com/ivan-hc/AppMan/main/applications/$APP/$APP.svg;
mv ./$APP.svg /home/$USER/.local/share/icons/;

echo "";
echo " Musicalypse is provided by https://musicalypse.creasource.net ";
echo "";

rm -R /opt/bin/tmp /opt/bin/$APP-installer
