#!/bin/sh

APP=flippy-qualitative-testbench

cd /opt/bin;
mkdir tmp;
cd ./tmp;
wget https://github.com/$(wget https://github.com/flippy-fyp/flippy-qualitative-testbench/releases/latest -O - | egrep '/.*/.*/.*AppImage' -o);
cd ..;
mv ./tmp/*mage ./$APP;
chmod a+x /opt/bin/$APP;

rm /home/$USER/.local/share/applications/$APP.desktop;
echo "[Desktop Entry]
Name=Flippy Qualitative Testbench
Exec=/opt/bin/flippy-qualitative-testbench
Comment=Score-follower qualitative testbench. Displays the timestamp output by a score-follower as a cursor on the score. 
Icon=flippy-qualitative-testbench
Type=Application
Categories=Audio;" >> /home/$USER/.local/share/applications/$APP.desktop;

wget https://raw.githubusercontent.com/ivan-hc/AppMan/main/applications/$APP/$APP.svg;
mv ./$APP.svg /home/$USER/.local/share/icons/;

echo "";
echo "      Flippy Qualitative Testbench is provided by";
echo "";
echo " https://github.com/flippy-fyp/flippy-qualitative-testbench";
echo "";

rm -R -f /opt/bin/tmp /opt/bin/$APP-installer /opt/bin/$APP-updater
