#!/bin/sh

APP=librewolf

cd /opt/bin;
mkdir tmp;
cd ./tmp;
wget https://gitlab.com/api/v4/projects/24386000/packages/generic/librewolf/latest/LibreWolf.x86_64.AppImage;
cd ..;
mv ./tmp/*mage ./$APP;
chmod a+x /opt/bin/$APP;

rm /home/$USER/.local/share/applications/$APP.desktop;
echo "[Desktop Entry]
Name=LibreWolf
Exec=/opt/bin/librewolf %u
Icon=librewolf
Comment=A fork of Firefox, focused on privacy, security and freedom.
Type=Application
MimeType=text/html;text/xml;application/xhtml+xml;x-scheme-handler/http;x-scheme-handler/https;application/x-xpinstall;application/pdf;application/json;
StartupWMClass=LibreWolf
Categories=Network;WebBrowser;
StartupNotify=true
Terminal=false
X-MultipleArgs=false
Keywords=Internet;WWW;Browser;Web;Explorer;
Actions=new-window;new-private-window;profilemanager;

[Desktop Action new-window]
Name=Open a New Window
Exec=/opt/bin/librewolf %u

[Desktop Action new-private-window]
Name=Open a New Private Window
Exec=/opt/bin/librewolf --private-window %u

[Desktop Action profilemanager]
Name=Open the Profile Manager
Exec=/opt/bin/librewolf --ProfileManager %u" >> /home/$USER/.local/share/applications/$APP.desktop;

wget https://raw.githubusercontent.com/ivan-hc/AppMan/main/applications/$APP/$APP.svg;
mv ./$APP.svg /home/$USER/.local/share/icons/;

echo "";
echo "  LibreWolf Web Browser is provided by";
echo "";
echo "  https://librewolf-community.gitlab.io ";
echo "";

rm -R -f /opt/bin/tmp /opt/bin/$APP-installer /opt/bin/$APP-updater
