#!/bin/sh

APP=spotify

cd /opt/bin;
mkdir tmp;
cd ./tmp;


wget -r -A spotify-1:*-x86_64.pkg.tar.zst -nd https://aur.andontie.net/x86_64/;
tar xf ./*.tar.zst;
mkdir $APP.AppDir;
mv ./opt ./$APP.AppDir;
cp ./$APP.AppDir/opt/spotify/*.desktop ./$APP.AppDir;
cp ./$APP.AppDir/opt/spotify/icons/spotify-linux-512.png ./$APP.AppDir/spotify-client.png;

echo '#!/bin/sh

HERE="$(dirname "$(readlink -f "${0}")")"
export PATH="${HERE}/opt/spotify/:${HERE}/opt/spotify/Apps/:${HERE}/opt/spotify/icons/:${HERE}/opt/spotify/locales/:${HERE}/opt/spotify/swiftshader/${PATH:+:$PATH}"
export LD_LIBRARY_PATH="${HERE}/opt/spotify/:${HERE}/opt/spotify/swiftshader/${LD_LIBRARY_PATH:+:$LD_LIBRARY_PATH}"
export XDG_DATA_DIRS="${HERE}/opt/spotify/${XDG_DATA_DIRS:+:$XDG_DATA_DIRS}"
export GSETTINGS_SCHEMA_DIR="${HERE}/opt/spotify/swiftshader/${GSETTINGS_SCHEMA_DIR:+:$GSETTINGS_SCHEMA_DIR}"
EXEC="${HERE}/opt/spotify/spotify"
exec "${EXEC}"' >> ./$APP.AppDir/AppRun;
chmod a+x ./$APP.AppDir/AppRun;

ARCH=x86_64 appimagetool -n ./$APP.AppDir;

cd ..;
mv ./tmp/*mage ./$APP;
chmod a+x /opt/bin/$APP;

rm /home/$USER/.local/share/applications/$APP.desktop;
echo "[Desktop Entry]
Type=Application
Name=Spotify
GenericName=Music Player
Icon=spotify
Exec=/opt/bin/spotify %U
Terminal=false
MimeType=x-scheme-handler/spotify;
Categories=Audio;Music;Player;AudioVideo;
StartupWMClass=spotify" >> /home/$USER/.local/share/applications/$APP.desktop;


wget https://raw.githubusercontent.com/ivan-hc/AppMan/main/applications/$APP/$APP.svg;
mv ./$APP.svg /home/$USER/.local/share/icons/;
echo "";

echo "   This version of Spotify comes from https://aur.andontie.net";
echo "                      'appman -i spotify' ";
echo "   to install a new and more updated version, when available ";

echo "";
rm -R /opt/bin/$APP-installer /opt/bin/tmp
