#!/bin/sh

APP=whatsapp-nativefier

cd /opt/bin;
mkdir tmp;
cd ./tmp;

v=$(wget -q https://api.github.com/repos/frealgagu/archlinux.whatsapp-nativefier/releases/latest -O - | grep -E tag_name | awk -F '[""]' '{print $4}')
wget https://github.com/frealgagu/archlinux.whatsapp-nativefier/releases/download/$v/whatsapp-nativefier-$v-x86_64.pkg.tar.zst;
tar xf ./*.tar.zst;
mkdir $APP.AppDir;
mv ./opt ./$APP.AppDir;
mv ./usr ./$APP.AppDir;
cp ./$APP.AppDir/usr/share/applications/*desktop ./$APP.AppDir;
cp ./$APP.AppDir/usr/share/icons/hicolor/192x192/apps/*png ./$APP.AppDir;

echo '#!/bin/sh

HERE="$(dirname "$(readlink -f "${0}")")"
export PATH="${HERE}/usr/bin/:${HERE}/opt/whatsapp-nativefier/${PATH:+:$PATH}"
export LD_LIBRARY_PATH="${HERE}/opt/whatsapp-nativefier/${LD_LIBRARY_PATH:+:$LD_LIBRARY_PATH}"
export XDG_DATA_DIRS="${HERE}/usr/share/${XDG_DATA_DIRS:+:$XDG_DATA_DIRS}"
EXEC="${HERE}/opt/whatsapp-nativefier/WhatsApp"
exec "${EXEC}"' >> ./$APP.AppDir/AppRun;
chmod a+x ./$APP.AppDir/AppRun;


ARCH=x86_64 appimagetool -n ./$APP.AppDir;

cd ..;
mv ./tmp/*mage ./$APP;
chmod a+x /opt/bin/$APP;

rm /home/$USER/.local/share/applications/$APP.desktop;
echo "[Desktop Entry]
Name=WhatsApp
Comment=WhatsApp desktop built with nativefier (electron)
Exec=/opt/bin/whatsapp-nativefier
Icon=whatsapp-nativefier
Encoding=UTF-8
StartupWMClass=whatsapp-nativefier-d40211
Terminal=false
StartupNotify=true
Type=Application
Categories=Network;Chat;InstantMessaging;Application;" >> /home/$USER/.local/share/applications/$APP.desktop;

wget https://raw.githubusercontent.com/ivan-hc/AppMan/main/applications/$APP/$APP.svg;
mv ./$APP.svg /home/$USER/.local/share/icons/;

echo "";
echo "         WhatsApp Nativefier is provided by";
echo "https://github.com/frealgagu/archlinux.whatsapp-nativefier";
echo "";

rm -R /opt/bin/tmp /opt/bin/$APP-installer
