#!/bin/sh

APP=cpu-x

cd /opt/bin;
mkdir tmp;
cd ./tmp;

v=$(wget -q https://api.github.com/repos/X0rg/CPU-X/releases/latest -O - | grep -E tag_name | awk -F '[""]' '{print $4}')
wget https://github.com/X0rg/CPU-X/releases/download/$v/CPU-X-$v-x86_64.AppImage;

cd ..;
mv ./tmp/*mage ./$APP;
chmod a+x /opt/bin/$APP;

rm /home/$USER/.local/share/applications/$APP.desktop;
echo "[Desktop Entry]
Name=CPU-X
Comment=Gathers information on CPU, motherboard and more
Comment[cs_CZ]=Shromažďuje informace o procesoru, základní desce a další
Comment[fr]=Récolte des informations sur le CPU, la carte-mère et plus
Comment[pt_BR]=Coleta informações sobre sua CPU, placa-mãe and mais
Comment[ru]=Сбор информации о процессоре, материнской плате и др.
Comment[zh]=收集有关 CPU 和主板等的信息
Exec=/opt/bin/cpu-x
Icon=cpu-x
Type=Application
Categories=GTK;System;
Terminal=false
Keywords=CPU;system;core;speed;clock;rate;Intel;AMD;motherboard;" >> /home/$USER/.local/share/applications/$APP.desktop;

wget https://raw.githubusercontent.com/ivan-hc/AppMan/main/applications/$APP/$APP.svg;
mv ./$APP.svg /home/$USER/.local/share/icons/;

echo "";
echo " CPU-X is provided by https://github.com/X0rg/CPU-X";
echo "";

rm -R /opt/bin/tmp /opt/bin/$APP-installer
