#!/bin/sh

APP=bts-ce-lite

cd /opt/bin;
mkdir tmp;
cd ./tmp;
wget https://github.com/$(wget https://github.com/bodastage/bts-ce-lite/releases/latest -O - | egrep '/.*/.*/.*AppImage' -o);
cd ..;
mv ./tmp/*mage ./$APP;
chmod a+x /opt/bin/$APP;

rm /home/$USER/.local/share/applications/$APP.desktop;
echo "[Desktop Entry]
Name=BTS-CE-Lite (Boda-Lite)
Exec=/opt/bin/bts-ce-lite
Comment=A cross platform vendor and technology agnostic telecommunication network management desktop application 
Icon=bts-ce-lite
Type=Application
Categories=Utility;" >> /home/$USER/.local/share/applications/$APP.desktop;

wget https://raw.githubusercontent.com/ivan-hc/AppMan/main/applications/$APP/$APP.svg;
mv ./$APP.svg /home/$USER/.local/share/icons/;

echo "";
echo " BTS-CE-Lite is provided by https://www.bodastage.org/bts-ce-lite ";
echo "";

rm -R -f /opt/bin/tmp /opt/bin/$APP-installer /opt/bin/$APP-updater
