#!/bin/sh

APP=minecraft-launcher

cd /opt/bin;
mkdir tmp;
cd ./tmp;
wget https://launcher.mojang.com/download/Minecraft.tar.gz;
tar xf Minecraft.tar.gz
cd ..;
mv ./tmp/$APP/$APP ./;
chmod a+x /opt/bin/$APP;

rm /home/$USER/.local/share/applications/$APP.desktop;
echo "[Desktop Entry]
Name=Minecraft Launcher
Comment=Game downloader and launcher for Minecraft
Exec=/opt/bin/minecraft-launcher
Icon=icon
Type=Application
Categories=Game;" >> /home/$USER/.local/share/applications/$APP.desktop;

wget https://raw.githubusercontent.com/ivan-hc/AppMan/main/applications/$APP/$APP.svg;
mv ./$APP.svg /home/$USER/.local/share/icons/;

echo "";
echo " Minecraft Launcher is provided by https://www.minecraft.net ";
echo "";

rm -R /opt/bin/tmp /opt/bin/$APP-installer
