#!/bin/sh

APP=mediathekview

cd /opt/bin;
mkdir tmp;
cd ./tmp;

v=$(wget -q https://api.github.com/repos/mediathekview/MediathekView/releases/latest -O - | grep -E tag_name | awk -F '[""]' '{print $4}')
wget https://github.com/mediathekview/MediathekView/releases/download/$v/MediathekView-$v-x86_64.AppImage;

cd ..;
mv ./tmp/*mage ./$APP;
chmod a+x /opt/bin/$APP;

rm /home/$USER/.local/share/applications/$APP.desktop;
echo "[Desktop Entry]
Name=MediathekView
Icon=mediathekview
Exec=/opt/bin/mediathekview
Type=Application
Categories=AudioVideo;
Comment=Mediatheken" >> /home/$USER/.local/share/applications/$APP.desktop;

wget https://raw.githubusercontent.com/ivan-hc/AppMan/main/applications/$APP/$APP.svg;
mv ./$APP.svg /home/$USER/.local/share/icons/;

echo "";
echo " MediathekView is provided by https://mediathekview.de";
echo "";

rm -R -f /opt/bin/tmp /opt/bin/$APP-installer /opt/bin/$APP-updater
