#!/bin/sh

APP=vk-music-fs

cd /opt/bin;
mkdir tmp;
cd ./tmp;
wget https://github.com/$(wget https://github.com/vodka2/vk-music-fs/releases/latest -O - | egrep '/.*/.*/.*64.AppImage' -o);
cd ..;
mv ./tmp/*mage ./$APP;
chmod a+x /opt/bin/$APP;

rm /home/$USER/.local/share/applications/$APP.desktop;
echo "[Desktop Entry]
Name=VK Music FS
Exec=/opt/bin/vk-music-fs
Comment=Listen to the music from VK using your favorite player and copy songs to your PC.
Icon=vk-music-fs
Type=Application
Categories=Audio;" >> /home/$USER/.local/share/applications/$APP.desktop;

wget https://raw.githubusercontent.com/ivan-hc/AppMan/main/applications/$APP/$APP.svg;
mv ./$APP.svg /home/$USER/.local/share/icons/;

echo "";
echo " VK Music FS is provided by https://github.com/vodka2 ";
echo "";

rm -R -f /opt/bin/tmp /opt/bin/$APP-installer /opt/bin/$APP-updater
