#!/bin/sh

cd /opt/bin;
wget https://raw.githubusercontent.com/ivan-hc/AppMan/main/applications/vivaldi-stable/vivaldi-stable-installer;
chmod a+x /opt/bin/vivaldi-stable-installer;
exec /opt/bin/vivaldi-stable-installer;
