#!/bin/sh

APP=sabaki

cd /opt/bin;
mkdir tmp;
cd ./tmp;
wget https://github.com/$(wget https://github.com/SabakiHQ/Sabaki/releases/latest -O - | egrep '/.*/.*/.*x64.AppImage' -o);
cd ..;
mv ./tmp/*mage ./$APP;
chmod a+x /opt/bin/$APP;

rm /home/$USER/.local/share/applications/$APP.desktop;
echo "[Desktop Entry]
Name=Sabaki
Exec=/opt/bin/sabaki --no-sandbox %U
Terminal=false
Type=Application
Icon=sabaki
StartupWMClass=Sabaki
Comment=An elegant Go/Baduk/Weiqi board and SGF editor for a more civilized age.
Categories=Game;" >> /home/$USER/.local/share/applications/$APP.desktop;

wget https://raw.githubusercontent.com/ivan-hc/AppMan/main/applications/$APP/$APP.svg;
mv ./$APP.svg /home/$USER/.local/share/icons/;

echo "";
echo " Sabaki is provided by https://sabaki.yichuanshen.de ";
echo "";

rm -R -f /opt/bin/tmp /opt/bin/$APP-installer /opt/bin/$APP-updater
