#!/bin/sh

APP=azpainter

cd /opt/bin;
mkdir tmp;
cd ./tmp;
wget https://github.com/$(wget https://github.com/Symbian9/azpainter/releases/tag/continuous -O - | egrep '/.*/.*/.*AppImage' -o);
cd ..;
mv ./tmp/*mage ./$APP;
chmod a+x /opt/bin/$APP;

rm /home/$USER/.local/share/applications/$APP.desktop;
echo "[Desktop Entry]
Name=AzPainter
Exec=/opt/bin/azpainter
Comment=A full color painting software for illustration drawing.
Icon=azpainter
Type=Application
Categories=Utility;System;Office;Game;Network,Education;AudioVideo;Graphics;" >> /home/$USER/.local/share/applications/$APP.desktop;

wget https://raw.githubusercontent.com/ivan-hc/AppMan/main/applications/$APP/$APP.svg;
mv ./$APP.svg /home/$USER/.local/share/icons/;

echo "";
echo " AzPainter is provided by https://github.com/Symbian9/azpainter ";
echo "";

rm -R -f /opt/bin/tmp /opt/bin/$APP-installer /opt/bin/$APP-updater
