#!/bin/sh

APP=minimal-podcasts-player

cd /opt/bin;
mkdir tmp;
cd ./tmp;
wget https://github.com/$(wget https://github.com/son-link/minimal-podcasts-player/releases/latest -O - | egrep '/.*/.*/.*AppImage' -o);
cd ..;
mv ./tmp/*mage ./$APP;
chmod a+x /opt/bin/$APP;

rm /home/$USER/.local/share/applications/$APP.desktop;
echo "[Desktop Entry]
Name=Minimal Podcasts Player
Exec=/opt/bin/minimal-podcasts-player
Comment=Subscribe, listen and (in the future) download your favorite podcasts, quickly and easily.
Icon=minimal-podcasts-player
Type=Application
Categories=Audio;" >> /home/$USER/.local/share/applications/$APP.desktop;

wget https://raw.githubusercontent.com/ivan-hc/AppMan/main/applications/$APP/$APP.svg;
mv ./$APP.svg /home/$USER/.local/share/icons/;

echo "";
echo "     Minimal Podcasts Player is provided by";
echo "";
echo " https://github.com/son-link/minimal-podcasts-player ";
echo "";

rm -R -f /opt/bin/tmp /opt/bin/$APP-installer /opt/bin/$APP-updater
