#!/bin/sh

APP=freecad

cd /opt/bin;
mkdir tmp;
cd ./tmp;
wget https://github.com/$(wget https://github.com/FreeCAD/FreeCAD-Bundle/releases/latest -O - | egrep '/.*/.*/.*AppImage' -o);
cd ..;
mv ./tmp/*AppImage ./$APP;
chmod a+x /opt/bin/$APP;
rm /home/$USER/.local/share/applications/$APP.desktop;
echo "[Desktop Entry]
Version=1.0
Name=FreeCAD
Exec=/opt/bin/freecad
Icon=freecad
Type=Application
Categories=Engineering;
Comment=Feature based Parametric Modeler
Terminal=false
StartupNotify=true
NoDisplay=false
MimeType=application/x-extension-fcstd;" >> /home/$USER/.local/share/applications/$APP.desktop;

wget https://raw.githubusercontent.com/ivan-hc/AppMan/main/applications/$APP/$APP.svg;
mv ./$APP.svg /home/$USER/.local/share/icons/;

echo "";
echo " FreeCAD is provided by https://www.freecadweb.org ";
echo "";

rm -R -f /opt/bin/tmp /opt/bin/$APP-installer /opt/bin/$APP-updater
