#!/bin/sh

APP=elements

cd /opt/bin;
mkdir tmp;
cd ./tmp;

v=$(wget -q https://api.github.com/repos/FlorianFe/Elements/releases/latest -O - | grep -E tag_name | awk -F '[""]' '{print $4}')
wget https://github.com/FlorianFe/Elements/releases/download/$v/Elements.AppImage;

cd ..;
mv ./tmp/*mage ./$APP;
chmod a+x /opt/bin/$APP;

rm /home/$USER/.local/share/applications/$APP.desktop;
echo "[Desktop Entry]
Name=Elements
Exec=/opt/bin/elements
Terminal=false
Type=Application
Icon=elements
StartupWMClass=Elements
Comment=A periodic table viewer desktop app
Categories=Utility;" >> /home/$USER/.local/share/applications/$APP.desktop;

wget https://raw.githubusercontent.com/ivan-hc/AppMan/main/applications/$APP/$APP.svg;
mv ./$APP.svg /home/$USER/.local/share/icons/;

echo "";
echo " Elements is provided by https://github.com/FlorianFe";
echo "";

rm -R /opt/bin/tmp /opt/bin/$APP-installer
