#!/bin/sh

APP=konquest

cd /opt/bin;
mkdir tmp;
cd ./tmp;

echo "app: konquest
binpatch: true

ingredients:
  dist: stable
  sources:
    - deb http://ftp.us.debian.org/debian/ stable main contrib non-free" >> recipe.yml

pkg2appimage ./recipe.yml;


ARCH=x86_64 appimagetool -n ./$APP/$APP.AppDir;

cd ..;

mv /opt/bin/tmp/*AppImage /opt/bin/$APP; 
chmod a+x /opt/bin/$APP;

rm /home/$USER/.local/share/applications/$APP.desktop;
echo "[Desktop Entry]
Icon=konquest
Name=Konquest
Name[af]=Konquest
Name[be]=Заваёва
Name[bn]=কনকোয়েস্ট
Name[br]=KAloubadur
Name[bs]=Konquest
Name[ca]=Konquest
Name[ca@valencia]=Konquest
Name[cs]=Konquest
Name[cy]=Konquest
Name[da]=Konquest
Name[de]=Konquest
Name[el]=Konquest
Name[en_GB]=Konquest
Name[eo]=Konkero
Name[es]=Konquest
Name[et]=Vallutus
Name[eu]=Konquest
Name[fi]=Konquest
Name[fr]=Konquest
Name[ga]=Konquest
Name[gl]=Konquest
Name[he]=Konquest
Name[hne]=कान्क्वेस्ट
Name[hr]=Konquest
Name[hu]=Hódítás
Name[is]=Geimstyrjöld
Name[it]=Konquest
Name[ja]=Konquest
Name[kk]=Konquest
Name[km]=Konquest
Name[ko]=Konquest
Name[lt]=Užkariautojas
Name[lv]=Konquest
Name[mk]=Konquest
Name[mr]=काँक्वेस्ट
Name[nb]=Konquest
Name[nds]=Konquest
Name[ne]=कनक्वेष्ट
Name[nl]=Konquest
Name[nn]=Konquest
Name[oc]=Konquest
Name[pl]=KPodbój
Name[pt]=Konquest
Name[pt_BR]=Konquest
Name[ro]=Konquest
Name[ru]=Konquest
Name[se]=Konquest
Name[sk]=Konquest
Name[sl]=Konquest
Name[sr]=К‑освајање
Name[sr@ijekavian]=К‑освајање
Name[sr@ijekavianlatin]=K‑osvajanje
Name[sr@latin]=K‑osvajanje
Name[sv]=Konquest
Name[ta]=கான்க்குவெஸ்ட்
Name[tg]=Истило
Name[tr]=Konquest
Name[ug]=Konquest
Name[uk]=Konquest
Name[vi]=Konquest
Name[wa]=Konquest
Name[xh]=Konquest
Name[x-test]=xxKonquestxx
Name[zh_CN]=Konquest
Name[zh_TW]=Konquest 征服
Exec=/opt/bin/konquest -qwindowtitle %c
Type=Application
GenericName=Galactic Strategy Game
GenericName[be]=Стратэгічная галактычная гульня
GenericName[bn]=গ্যালাকটিক কৌশলের খেলা
GenericName[bs]=Galaktička strateška igra
GenericName[ca]=Joc d'estratègia galàctica
GenericName[ca@valencia]=Joc d'estratègia galàctica
GenericName[cs]=Strategická galaktická hra
GenericName[cy]=Gêm Strategaeth Galaethol
GenericName[da]=Galaktisk strategispil
GenericName[de]=Galaktisches Strategiespiel
GenericName[el]=Γαλαξιακό παιχνίδι στρατηγικής
GenericName[en_GB]=Galactic Strategy Game
GenericName[eo]=Galaksia strategiludo
GenericName[es]=Juego de estrategia espacial
GenericName[et]=Galaktiline strateegiamäng
GenericName[eu]=Estrategia galaktikoaren jokoa
GenericName[fa]=بازی Galactic Strategy
GenericName[fi]=Galaktinen strategiapeli
GenericName[fr]=Jeu de stratégie galactique
GenericName[ga]=Cluiche Réaltrach Straitéise
GenericName[gl]=Xogo de estratexia galáctica
GenericName[he]=משחק אסטרטגיה גלקטי
GenericName[hne]=गेलेक्टिक कौसल वाले खेल
GenericName[hr]=Galaktička igra strategije
GenericName[hu]=Galaktikus stratégiai játék
GenericName[is]=Herkænskuleikur
GenericName[it]=Gioco di strategia galattica
GenericName[ja]=宇宙戦略ゲーム
GenericName[kk]=Галактикалық стратегия ойны
GenericName[km]=ល្បែង​យុទ្ធសាស្ត្រ​ផ្កាយ
GenericName[ko]=은하 전략 게임
GenericName[lt]=Galaktikos strateginis žaidimas
GenericName[lv]=Stratēģiska kosmiskā spēle
GenericName[mk]=Игра на галактичка стратегија
GenericName[mr]=आकाशगंगेतील रणनीतिक खेळ
GenericName[nb]=Strategispillet Galactic
GenericName[nds]=Galaktsch Strategiespeel
GenericName[ne]=ग्यालाक्टिक रणनीति खेल
GenericName[nl]=Strategisch ruimtespel
GenericName[nn]=Galaktisk strategispel
GenericName[pl]=Gra strategiczna w kosmosie
GenericName[pt]=Jogo de Estratégia Galáctica
GenericName[pt_BR]=Jogo de estratégia galáctica
GenericName[ro]=Joc de strategie galactică
GenericName[ru]=Стратегическая галактическая игра
GenericName[se]=Strategiijaspeallu Galactic
GenericName[sk]=Galaktická strategická hra
GenericName[sl]=Galaktična strateška igra
GenericName[sr]=Игра галактичке стратегије
GenericName[sr@ijekavian]=Игра галактичке стратегије
GenericName[sr@ijekavianlatin]=Igra galaktičke strategije
GenericName[sr@latin]=Igra galaktičke strategije
GenericName[sv]=Galaktiskt strategispel
GenericName[ta]=கலாட்டிக் தந்திர விளையாட்டு
GenericName[tr]=Galaktik Strateji Oyunu
GenericName[ug]=سامانيولى ئىستراتېگىيە ئويۇنى
GenericName[uk]=Галактична гра-стратегія
GenericName[wa]=Djeu di stratedjeye galactike
GenericName[x-test]=xxGalactic Strategy Gamexx
GenericName[zh_CN]=星际策略游戏
GenericName[zh_TW]=銀河戰略遊戲
Terminal=false
X-DocPath=konquest/index.html
X-KDE-StartupNotify=true
X-DBUS-StartupType=Multi
Categories=Qt;KDE;Game;StrategyGame;
X-DBUS-ServiceName=org.kde.konquest" >> /home/$USER/.local/share/applications/$APP.desktop;

wget https://raw.githubusercontent.com/ivan-hc/AppMan/main/applications/$APP/$APP.svg;
mv ./$APP.svg /home/$USER/.local/share/icons/;

echo "";
echo "   This AppImage was created from Debian Stable using";
echo "";
echo "       https://github.com/AppImage/pkg2appimage ";
echo "";

rm -R -f /opt/bin/tmp /opt/bin/$APP-installer /opt/bin/$APP-updater
