#!/bin/sh

APP=bazecor

cd /opt/bin;
mkdir tmp;
cd ./tmp;
wget https://github.com/$(wget https://github.com/Dygmalab/Bazecor/releases/latest -O - | egrep '/.*/.*/.*AppImage' -o);
cd ..;
mv ./tmp/*mage ./$APP;
chmod a+x /opt/bin/$APP;

rm /home/$USER/.local/share/applications/$APP.desktop;
echo "[Desktop Entry]
Name=Bazecor
Exec=/opt/bin/bazecor
Comment=Graphical configurator for Dygma Raise
Icon=bazecor
Type=Application
Categories=Utility;" >> /home/$USER/.local/share/applications/$APP.desktop;

wget https://raw.githubusercontent.com/ivan-hc/AppMan/main/applications/$APP/$APP.svg;
mv ./$APP.svg /home/$USER/.local/share/icons/;

echo "";
echo " Bazecor is provided by https://github.com/Dygmalab/Bazecor ";
echo "";

rm -R -f /opt/bin/tmp /opt/bin/$APP-installer /opt/bin/$APP-updater
