#!/bin/sh

APP=etcher

cd /opt/bin;
mkdir tmp;
cd ./tmp;
wget https://github.com/$(wget https://github.com/balena-io/etcher/releases/latest -O - | egrep '/.*/.*/.*x64.AppImage' -o);
cd ..;
mv ./tmp/*mage ./$APP;
chmod a+x /opt/bin/$APP;

rm /home/$USER/.local/share/applications/$APP.desktop;
echo "[Desktop Entry]
Name=balenaEtcher
Exec=/opt/bin/etcher --no-sandbox %U
Terminal=false
Type=Application
Icon=balena-etcher-electron
StartupWMClass=balenaEtcher
Comment=Flash OS images to SD cards and USB drives, safely and easily.
MimeType=x-scheme-handler/etcher;
Categories=Utility;" >> /home/$USER/.local/share/applications/$APP.desktop;

wget https://raw.githubusercontent.com/ivan-hc/AppMan/main/applications/$APP/$APP.svg;
mv ./$APP.svg /home/$USER/.local/share/icons/;

echo "";
echo " Balena Etcher is provided by https://www.balena.io/etcher ";
echo "";

rm -R -f /opt/bin/tmp /opt/bin/$APP-installer /opt/bin/$APP-updater
