#!/bin/sh

APP=blensor

cd /opt/bin;
mkdir tmp;
cd ./tmp;
wget https://www.blensor.org/dload/Blensor-x64.AppImage;
cd ..;
mv ./tmp/*mage ./$APP;
chmod a+x /opt/bin/$APP;

rm /home/$USER/.local/share/applications/$APP.desktop;
echo "[Desktop Entry]
Name=BlenSor
Exec=/opt/bin/blensor
Comment=Free Open Source Simulation Package for Light Detection and Ranging (LIDAR/LADAR) and Kinect sensors
Icon=blensor
Type=Application
Categories=Graphics;" >> /home/$USER/.local/share/applications/$APP.desktop;

wget https://raw.githubusercontent.com/ivan-hc/AppMan/main/applications/$APP/$APP.svg;
mv ./$APP.svg /home/$USER/.local/share/icons/;

echo "";
echo " BlenSor is provided by https://www.blensor.org ";
echo "";

rm -R -f /opt/bin/tmp /opt/bin/$APP-installer /opt/bin/$APP-updater
