#!/bin/sh

cd /opt/bin;
wget https://raw.githubusercontent.com/ivan-hc/AppMan/main/applications/platform-tools/platform-tools-installer;
chmod a+x /opt/bin/platform-tools-installer;
exec /opt/bin/platform-tools-installer;
