#!/bin/sh

APP=book-manager

cd /opt/bin;
mkdir tmp;
cd ./tmp;
wget https://github.com/$(wget https://github.com/bdTechies/book-manager/releases/latest -O - | egrep '/.*/.*/.*AppImage' -o);
cd ..;
mv ./tmp/*mage ./$APP;
chmod a+x /opt/bin/$APP;

rm /home/$USER/.local/share/applications/$APP.desktop;
echo "[Desktop Entry]
Name=Book Manager
Comment=A simple personal library management application.
Exec=/opt/bin/book-manager
Terminal=false
Type=Application
Icon=book-manager
StartupWMClass=Book Manager
Categories=Utility;" >> /home/$USER/.local/share/applications/$APP.desktop;

wget https://raw.githubusercontent.com/ivan-hc/AppMan/main/applications/$APP/$APP.svg;
mv ./$APP.svg /home/$USER/.local/share/icons/;

echo "";
echo " Boock Manager is provided by https://github.com/bdTechies ";
echo "";

rm -R /opt/bin/tmp /opt/bin/$APP-installer
