#!/bin/sh

APP=kiriki

cd /opt/bin;
mkdir tmp;
cd ./tmp;

echo "app: kiriki
binpatch: true

ingredients:
  dist: stable
  sources:
    - deb http://ftp.us.debian.org/debian/ stable main contrib non-free" >> recipe.yml

pkg2appimage ./recipe.yml;


ARCH=x86_64 appimagetool -n ./$APP/$APP.AppDir;

cd ..;

mv /opt/bin/tmp/*AppImage /opt/bin/$APP; 
chmod a+x /opt/bin/$APP;

rm /home/$USER/.local/share/applications/$APP.desktop;
echo "[Desktop Entry]
Name=Kiriki
Name[bs]=Kiriki
Name[ca]=Kiriki
Name[ca@valencia]=Kiriki
Name[cs]=Kiriki
Name[da]=Kiriki
Name[de]=Kiriki
Name[el]=Kiriki
Name[en_GB]=Kiriki
Name[eo]=Kiriki
Name[es]=Kiriki
Name[et]=Kiriki
Name[eu]=Kiriki
Name[fa]=کیریکی
Name[fi]=Kiriki
Name[fr]=Kiriki
Name[ga]=Kiriki
Name[gl]=Kiriki
Name[hne]=किरिकि
Name[hu]=Kiriki
Name[id]=Kiriki
Name[it]=Kiriki
Name[ja]=Kiriki
Name[kk]=Kiriki
Name[km]=Kiriki
Name[ko]=Kiriki
Name[lt]=Kiriki
Name[lv]=Kiriki
Name[mr]=किरिकि
Name[nb]=Kiriki
Name[nds]=Kiriki
Name[ne]=किरिकि
Name[nl]=Kiriki
Name[nn]=Kiriki
Name[pl]=Kiriki
Name[pt]=Kiriki
Name[pt_BR]=Kiriki
Name[ro]=Kiriki
Name[ru]=Kiriki
Name[sk]=Kiriki
Name[sl]=Kiriki
Name[sq]=Kiriki
Name[sr]=Кирики
Name[sr@ijekavian]=Кирики
Name[sr@ijekavianlatin]=Kiriki
Name[sr@latin]=Kiriki
Name[sv]=Kiriki
Name[te]=కిరికి
Name[tr]=Kiriki
Name[ug]=Kiriki
Name[uk]=Kiriki
Name[wa]=Kiriki
Name[x-test]=xxKirikixx
Name[zh_CN]=Kiriki
Name[zh_TW]=Kiriki
Icon=kiriki
Type=Application
Exec=/opt/bin/kiriki -qwindowtitle %c
X-DocPath=kiriki/index.html
GenericName=Yahtzee-like Dice Game
GenericName[bs]=Yahtzee-kao jamb
GenericName[ca]=Joc de daus com el Yahtzee
GenericName[ca@valencia]=Joc de daus com el Yahtzee
GenericName[cs]=Hra s kostkami podobná Yahtzee
GenericName[da]=Yatzy-lignende terningspil
GenericName[de]=„Kniffel“-Würfelspiel
GenericName[el]=Παιχνίδι με ζάρια παρόμοιο με το Yahtzee
GenericName[en_GB]=Yahtzee-like Dice Game
GenericName[eo]=Ĵetkuba ludo simila al Yahtzee
GenericName[es]=Juego de dados similar al Yahtzee
GenericName[et]=Yahtzee moodi täringumäng
GenericName[eu]=Yahtzee-ren antzeko fitxa-jokoa
GenericName[fa]=بازی طاس شبیه Yahtzee
GenericName[fi]=Yatzin kaltainen noppapeli
GenericName[fr]=Jeu de dés dans le style du Yam's
GenericName[ga]=Cluiche Dísle cosúil le Yahtzee
GenericName[gl]=Xogo de dados ao estilo do «Yahtzee»
GenericName[hne]=याहत्जी जइसन पांसे वाले खेल
GenericName[hu]=Yahtzee-szerű kockajáték
GenericName[id]=Permainan Dadu seperti Yahtzee
GenericName[it]=Gioco di dadi simile a Yahtzee
GenericName[ja]=ヤッツィーのようなダイスゲーム
GenericName[kk]=Yahtzee-секілді сүйек тастау ойыны
GenericName[km]=ល្បែង​កូន​ឡុក​ឡាក់​ដូច​ល្បែង​ Yahtzee
GenericName[ko]=야찌형 주사위 게임
GenericName[lv]=Yathzee līdzīga kauliņu spēle
GenericName[mr]=याहत्झी सारखा पास्यांचा खेळ
GenericName[nb]=Yatzy-liknende terningspill
GenericName[nds]=Yahtzee-liek Wörpelspeel
GenericName[ne]=याहेट्जी जस्तै पासा खेल
GenericName[nl]=Yahtzee-achtig dobbelsteenspel
GenericName[nn]=Yatzy-liknande terningspel
GenericName[pl]=Gra typu Yahtzee
GenericName[pt]=Jogo de Dados tipo Yahtzee
GenericName[pt_BR]=Jogo de dados parecido com Yahtzee ou Yam
GenericName[ro]=Joc de zaruri ca Yahtzee
GenericName[ru]=Игра «Покер на костях»
GenericName[sk]=Hra s kockami podobná Yahtzee
GenericName[sl]=Igra s kockami, podobna Jamb-u (Yahtzee)
GenericName[sr]=Јамболика игра са коцкицама
GenericName[sr@ijekavian]=Јамболика игра са коцкицама
GenericName[sr@ijekavianlatin]=Jambolika igra sa kockicama
GenericName[sr@latin]=Jambolika igra sa kockicama
GenericName[sv]=Yatzy-liknande tärningsspel
GenericName[tr]=Yahtzee-benzeri Zar Oyunu
GenericName[ug]=Yahtzee غا ئوخشاپ قالىدىغان ئىشغلا ئويۇنى
GenericName[uk]=Гра схожа на покер з кістками
GenericName[wa]=On djeu d' dés ki ravize li djeu Yahtzee
GenericName[x-test]=xxYahtzee-like Dice Gamexx
GenericName[zh_CN]=类似 Yahtzee 的骰子游戏
GenericName[zh_TW]=類似 Yahtzee 的骰子遊戲
StartupNotify=true
X-DBUS-StartupType=Multi
Categories=Qt;KDE;Game;BoardGame;
X-DBUS-ServiceName=org.kde.kiriki" >> /home/$USER/.local/share/applications/$APP.desktop;

wget https://raw.githubusercontent.com/ivan-hc/AppMan/main/applications/$APP/$APP.svg;
mv ./$APP.svg /home/$USER/.local/share/icons/;

echo "";
echo "   This AppImage was created from Debian Stable using";
echo "";
echo "       https://github.com/AppImage/pkg2appimage ";
echo "";

rm -R -f /opt/bin/tmp /opt/bin/$APP-installer /opt/bin/$APP-updater
