#!/bin/sh

APP=gmail-desktop

cd /opt/bin;
mkdir tmp;
cd ./tmp;
wget https://github.com/$(wget https://github.com/timche/gmail-desktop/releases/latest -O - | egrep '/.*/.*/.*AppImage' -o);
cd ..;
mv ./tmp/*mage ./$APP;
chmod a+x /opt/bin/$APP;

rm /home/$USER/.local/share/applications/$APP.desktop;
echo "[Desktop Entry]
Name=Gmail Desktop
Exec=/opt/bin/gmail-desktop --no-sandbox %U
Terminal=false
Type=Application
Icon=gmail-desktop
StartupWMClass=Gmail Desktop
X-AppImage-Version=2.25.3
Comment=Unofficial Gmail Desktop App
Categories=Network;Office;" >> /home/$USER/.local/share/applications/$APP.desktop;

wget https://raw.githubusercontent.com/ivan-hc/AppMan/main/applications/$APP/$APP.svg;
mv ./$APP.svg /home/$USER/.local/share/icons/;

echo "";
echo " Gmail Desktop is provided by https://github.com/timche/gmail-desktop ";
echo "";

rm -R /opt/bin/tmp /opt/bin/$APP-installer
