#!/bin/sh

APP=kjumpingcube

cd /opt/bin;
mkdir tmp;
cd ./tmp;

echo "app: kjumpingcube
binpatch: true

ingredients:
  dist: stable
  sources:
    - deb http://ftp.us.debian.org/debian/ stable main contrib non-free" >> recipe.yml

pkg2appimage ./recipe.yml;


ARCH=x86_64 appimagetool -n ./$APP/$APP.AppDir;

cd ..;

mv /opt/bin/tmp/*AppImage /opt/bin/$APP; 
chmod a+x /opt/bin/$APP;

rm /home/$USER/.local/share/applications/$APP.desktop;
echo "[Desktop Entry]
Name=KJumpingCube
Name[af]=Kjumpingcube
Name[be]=Скокаючы кубік
Name[bn]=কে-জাম্পিংকিউব
Name[br]=KDiñsALamm
Name[bs]=KJumpingCube
Name[ca]=KJumpingCube
Name[ca@valencia]=KJumpingCube
Name[cs]=KJumpingCube
Name[cy]=KJumpingCube
Name[da]=KJumpingCube
Name[de]=KJumpingCube
Name[el]=KJumpingCube
Name[en_GB]=KJumpingCube
Name[eo]=KJumpingCube
Name[es]=KJumpingCube
Name[et]=KJumpingCube
Name[eu]=KJumpingCube
Name[fa]=مکعب پرنده
Name[fi]=KJumpingCube
Name[fr]=KJumpingCube
Name[ga]=KJumpingCube
Name[gl]=KJumpingCube
Name[he]=KJumpingCube
Name[hne]=के-जम्पिंगक्यूब
Name[hr]=KJumpingCube
Name[hu]=Ugráló kocka
Name[id]=KJumpingCube
Name[is]=Hoppandi kubbur
Name[it]=KJumpingCube
Name[ja]=KJumpingCube
Name[kk]=KJumpingCube
Name[km]=KJumpingCube
Name[ko]=KJumpingCube
Name[lt]=KJumpingCube
Name[lv]=KJumpingCube
Name[mk]=KJumpingCube
Name[mr]=के-जम्पिंगक्यूब
Name[nb]=KJumpingCube
Name[nds]=KJumpingCube
Name[ne]=केडीई जम्पिङ क्युब
Name[nl]=KJumpingCube
Name[nn]=KJumpingCube
Name[pa]=ਕੇ-ਜੰਪ ਘਣ
Name[pl]=KSkaczącySześcian
Name[pt]=KJumpingCube
Name[pt_BR]=KJumpingCube
Name[ro]=Cubul săritor
Name[ru]=KJumpingCube
Name[se]=KJumpingCube
Name[sk]=KJumpingCube
Name[sl]=KJumpingCube
Name[sq]=KJumpingCube
Name[sr]=К‑скочикоцка
Name[sr@ijekavian]=К‑скочикоцка
Name[sr@ijekavianlatin]=K‑skočikocka
Name[sr@latin]=K‑skočikocka
Name[sv]=Hoppande kuben
Name[ta]=கேகுதிக்கும் கனசதுரம்
Name[tg]=KКубикҳои Ҷиҳанда
Name[tr]=KJumpingCube
Name[ug]=KJumpingCube
Name[uk]=KJumpingCube
Name[vi]=KJumpingCube
Name[wa]=KJumpingCube
Name[xh]=Ityhubhu yeKJumping
Name[x-test]=xxKJumpingCubexx
Name[zh_CN]=KJumpingCube
Name[zh_TW]=KJumpingCube 跳躍立方體
Exec=/opt/bin/kjumpingcube -qwindowtitle %c
Icon=kjumpingcube
Type=Application
X-DocPath=kjumpingcube/index.html
GenericName=Territory Capture Game
GenericName[bs]=Igra osvajanja teritorija
GenericName[ca]=Joc de conquesta del territori
GenericName[ca@valencia]=Joc de conquesta del territori
GenericName[cs]=Hra na zabírání území
GenericName[da]=Spil om at indtage områder
GenericName[de]=Eroberungsspiel
GenericName[el]=Παιχνίδι κατάληψης περιοχών
GenericName[en_GB]=Territory Capture Game
GenericName[es]=Juego de conquista del territorio
GenericName[et]=Mänguala vallutamise mäng
GenericName[eu]=Territorioak bereganatzeko jokoa
GenericName[fi]=Alueenvaltauspeli
GenericName[fr]=Jeu de capture de territoires
GenericName[ga]=Cluiche Gabhála Talaimh
GenericName[gl]=Xogo de captura de territorios
GenericName[hu]=Területfoglaló
GenericName[id]=Permainan Menguasai Wilayah
GenericName[it]=Gioco di conquista del territorio
GenericName[ja]=陣地獲得ゲーム
GenericName[kk]=Жер жаулау ойны
GenericName[km]=ល្បែង​ចាប់​យក​ដែនដី
GenericName[ko]=땅따먹기 게임
GenericName[lt]=Teritorijos užgrobimo žaidimas
GenericName[lv]=Teritorijas ieņemšanas spēle
GenericName[mr]=क्षेत्र अंकित खेळ
GenericName[nb]=Spill basert på områdekapring
GenericName[nl]=Landverovertjespel
GenericName[nn]=Spel basert på områdekapring
GenericName[pl]=Gra w zajmowanie terytorium
GenericName[pt]=Jogo de Captura do Território
GenericName[pt_BR]=Jogo de captura de território
GenericName[ro]=Joc de capturare a teritoriului
GenericName[ru]=Захват территорий
GenericName[sk]=Hra na obsadzovanie území
GenericName[sl]=Igra osvajanja ozemlja
GenericName[sr]=Игра заузимања територије
GenericName[sr@ijekavian]=Игра заузимања територије
GenericName[sr@ijekavianlatin]=Igra zauzimanja teritorije
GenericName[sr@latin]=Igra zauzimanja teritorije
GenericName[sv]=Terrängerövring
GenericName[tr]=Bölge Ele Geçirme Oyunu
GenericName[ug]=تېررىتورىيە ئىگىلەش ئويۇنى
GenericName[uk]=Гра на захоплення територій
GenericName[x-test]=xxTerritory Capture Gamexx
GenericName[zh_CN]=版块占领游戏
GenericName[zh_TW]=領土爭奪戰
Comment=Territory Capture Game
Comment[ca]=Joc de conquesta del territori
Comment[ca@valencia]=Joc de conquesta del territori
Comment[cs]=Hra na zabírání území
Comment[da]=Spil om at indtage områder
Comment[de]=Eroberungsspiel
Comment[el]=Παιχνίδι κατάληψης περιοχών
Comment[en_GB]=Territory Capture Game
Comment[es]=Juego de conquista de territorios
Comment[et]=Mänguala vallutamise mäng
Comment[fi]=Alueenvaltauspeli
Comment[fr]=Jeu de capture de territoires
Comment[gl]=Xogo de captura de territorios.
Comment[id]=Permainan Menguasai Wilayah
Comment[it]=Gioco di conquista del territorio
Comment[ko]=땅따먹기 게임
Comment[nl]=Landverovertjespel
Comment[nn]=Spel basert på områdekapring
Comment[pl]=Gra w zajmowanie terytorium
Comment[pt]=Jogo de Captura do Território
Comment[pt_BR]=Jogo de captura de território
Comment[ru]=Захват территорий
Comment[sk]=Hra na obsadzovanie území
Comment[sl]=Igra osvajanja ozemlja
Comment[sr]=Игра заузимања територије
Comment[sr@ijekavian]=Игра заузимања територије
Comment[sr@ijekavianlatin]=Igra zauzimanja teritorije
Comment[sr@latin]=Igra zauzimanja teritorije
Comment[sv]=Territorium-erövringsspel
Comment[tr]=Bölge Ele Geçirme Oyunu
Comment[uk]=Гра на захоплення територій
Comment[x-test]=xxTerritory Capture Gamexx
Comment[zh_CN]=版块占领游戏
Comment[zh_TW]=領土爭奪戰
Terminal=false
StartupNotify=true
X-DBUS-StartupType=Multi
Categories=Qt;KDE;Game;StrategyGame;
X-DBUS-ServiceName=org.kde.kjumpingcube" >> /home/$USER/.local/share/applications/$APP.desktop;

wget https://raw.githubusercontent.com/ivan-hc/AppMan/main/applications/$APP/$APP.svg;
mv ./$APP.svg /home/$USER/.local/share/icons/;

echo "";
echo "   This AppImage was created from Debian Stable using";
echo "";
echo "       https://github.com/AppImage/pkg2appimage ";
echo "";

rm -R -f /opt/bin/tmp /opt/bin/$APP-installer /opt/bin/$APP-updater
