#!/bin/sh

cd /opt/bin
mkdir tmp;
cd tmp;
wget https://download.opensuse.org/repositories/home:/munix9/AppImage/celestia-latest-x86_64.AppImage;
cd ..;
mv ./tmp/celestia*AppImage ./celestia;
chmod a+x ./celestia;

echo "[Desktop Entry]
Version=1.0
Name=Celestia (GTK)
GenericName=Space Simulator (AppImage-1.6.2.2)
GenericName[de]=Weltraum-Simulator (AppImage-1.6.2.2)
Comment=Explore the Universe in this detailed space simulation
Comment[de]=Erkunde das Universum in dieser detaillierten Weltraumsimulation
Type=Application
Categories=Astronomy;Education;Science;GTK;
Icon=celestia
Exec=/opt/bin/celestia %f
Terminal=false
MimeType=application/x-celestia-script;" >> /home/$USER/.local/share/applications/celestia.desktop;
wget wget https://raw.githubusercontent.com/ivan-hc/AppMan/main/applications/celestia/celestia.svg;
mv ./celestia.svg /home/$USER/.local/share/icons/;
rm -R /opt/bin/tmp /opt/bin/celestia-installer
