#!/bin/sh

cd /opt/openshot;
mkdir tmp;
cd tmp;
v=$(wget -q https://api.github.com/repos/OpenShot/openshot-qt/releases/latest -O - | grep -E tag_name | awk -F '[""]' '{print $4}')
wget https://github.com/OpenShot/openshot-qt/releases/download/$v/OpenShot-$v-x86_64.AppImage;
cd ..
mv ./tmp/*mage ./openshot
chmod a+x ./openshot
rmdir ./tmp
