#!/bin/sh

cd /opt/bin;
mkdir tmp;
cd tmp;
v=$(wget -q https://api.github.com/repos/OpenShot/openshot-qt/releases/latest -O - | grep -E tag_name | awk -F '[""]' '{print $4}')
wget https://github.com/OpenShot/openshot-qt/releases/download/$v/OpenShot-$v-x86_64.AppImage;
cd ..
mv ./tmp/*mage ./openshot;
chmod a+x ./openshot;
rm /home/$USER/.local/share/applications/openshot.desktop;
echo '[Desktop Entry]
Name=OpenShot Video Editor
GenericName=Video Editor
X-GNOME-FullName=OpenShot Video Editor
Comment=Create and edit amazing videos and movies
Exec=/opt/bin/openshot %F
Terminal=false
Type=Application
Icon=openshot
Categories=GNOME;GTK;AudioVideo;Video;AudioVideoEditing;
MimeType=application/vnd.openshot-qt-project;
X-AppInstall-Package=openshot-qt
Path=
StartupNotify=true' >> /home/$USER/.local/share/applications/openshot.desktop;
wget https://raw.githubusercontent.com/ivan-hc/AppMan/main/applications/openshot/openshot.svg;
mv ./openshot.svg /home/$USER/.local/share/icons/;
echo "";
echo " OpenShot QT AppImage is provided by https://github.com/OpenShot ";
echo "";
rm -R -f /opt/bin/tmp /opt/bin/openshot-installer /opt/bin/openshot-updater
