#!/bin/sh

APP=openhv

cd /opt/bin;
mkdir tmp;
cd ./tmp;
wget https://github.com/$(wget https://github.com/OpenHV/OpenHV/releases/latest -O - | egrep '/.*/.*/.*AppImage' -o);
cd ..;
mv ./tmp/*mage ./$APP;
chmod a+x /opt/bin/$APP;

rm /home/$USER/.local/share/applications/$APP.desktop;
echo "[Desktop Entry]
Name=OpenHV
Exec=/opt/bin/openhv
Comment=A mod for OpenRA based on the Hard Vacuum design by Daniel Cook. It aims to be an open content game with no exceptions.
Icon=openhv
Type=Application
Categories=Game;" >> /home/$USER/.local/share/applications/$APP.desktop;

wget https://raw.githubusercontent.com/ivan-hc/AppMan/main/applications/$APP/$APP.svg;
mv ./$APP.svg /home/$USER/.local/share/icons/;

echo "";
echo " OpenHV is provided by https://openhv.itch.io/openhv ";
echo "";

rm -R -f /opt/bin/tmp /opt/bin/$APP-installer /opt/bin/$APP-updater
