#!/bin/sh

APP=moonplayer

cd /opt/bin;
mkdir tmp;
cd ./tmp;
wget https://github.com/$(wget https://github.com/coslyk/moonplayer/releases/latest -O - | egrep '/.*/.*/.*x86_64.AppImage' -o);
cd ..;
mv ./tmp/*mage ./$APP;
chmod a+x /opt/bin/$APP;

rm /home/$USER/.local/share/applications/$APP.desktop;
echo "[Desktop Entry]
Categories=AudioVideo;Player;
Comment[zh_CN]=播放本地及网络视频
Comment=Play local or online videos
Exec=/opt/bin/moonplayer %U
GenericName[zh_CN]=视频播放器
GenericName=Media Player
Icon=moonplayer
MimeType=video/x-theora+ogg;video/x-ogm+ogg;video/x-msvideo;video/x-msvideo;video/x-ms-wmv;video/x-ms-asf;video/x-matroska;video/x-flv;video/vnd.rn-realvideo;video/quicktime;video/mpeg;video/mp4;audio/x-wav;audio/x-vorbis+ogg;audio/x-vorbis+ogg;audio/x-scpls;audio/x-ms-wma;audio/x-mpegurl;audio/x-mpegurl;audio/x-matroska;audio/x-adpcm;audio/vnd.rn-realaudio;audio/vnd.rn-realaudio;audio/mpeg;audio/mpeg;audio/mp4;audio/mp2;audio/ac3;application/xspf+xml;x-scheme-handler/moonplayer;x-scheme-handler/moonplayers;
Name[zh_CN]=MoonPlayer
Name=MoonPlayer
StartupNotify=true
StartupWMClass=MoonPlayer
Terminal=false
Type=Application
X-KDE-SubstituteUID=false" >> /home/$USER/.local/share/applications/$APP.desktop;

wget https://raw.githubusercontent.com/ivan-hc/AppMan/main/applications/$APP/$APP.svg;
mv ./$APP.svg /home/$USER/.local/share/icons/;

echo "";
echo " MoonPlayer is provided by https://coslyk.github.io/moonplayer.html ";
echo "";

rm -R /opt/bin/tmp /opt/bin/$APP-installer
