#!/bin/sh

APP=btop

cd /opt/bin;
mkdir tmp;
cd ./tmp;
mkdir $APP.AppDir;
cd ./$APP.AppDir;

wget https://github.com/$(wget https://github.com/aristocratos/btop/releases/latest -O - | egrep '/.*/.*/.*linux-x86_64.tbz' -o);
tar xf ./*.tbz;
rm ./*.tbz;
cd ..;
touch ./$APP.AppDir/$APP.png;
echo "[Desktop Entry]
Name=btop
Exec=btop
Icon=btop
Type=Application
Categories=Utility;" >> ./$APP.AppDir/$APP.desktop;
cp ./$APP.AppDir/usr/share/applications/*desktop ./$APP.AppDir;
cp ./$APP.AppDir/usr/share/PATH-TO-ICON/*png ./$APP.AppDir;

echo '#!/bin/sh

SELF=$(readlink -f "$0")
HERE=${SELF%/*}
export PATH="${HERE}/bin/:${HERE}/themes/${PATH:+:$PATH}"
EXEC="${HERE}/bin/btop"
EXEC=$(grep -e '^Exec=.*' "${HERE}"/*.desktop | head -n 1 | cut -d "=" -f 2 | cut -d " " -f 1)
exec "${EXEC}" "$@"' >> ./$APP.AppDir/AppRun;
chmod a+x ./$APP.AppDir/AppRun;

ARCH=x86_64 appimagetool -n ./$APP.AppDir;

cd ..;
mv ./tmp/*mage ./$APP;
chmod a+x /opt/bin/$APP;

echo "";
echo "   Btop is provided by https://github.com/aristocratos/btop";
echo "";

rm -R -f /opt/bin/tmp /opt/bin/$APP-installer /opt/bin/$APP-updater
