#!/bin/sh

APP=gsequencer

cd /opt/bin;
mkdir tmp;
cd ./tmp;
wget https://github.com/$(wget https://github.com/gsequencer/gsequencer/releases/latest -O - | egrep '/.*/.*/.*AppImage' -o);
cd ..;
mv ./tmp/*mage ./$APP;
chmod a+x /opt/bin/$APP;

rm /home/$USER/.local/share/applications/$APP.desktop;
echo "[Desktop Entry]
Name=Advanced Gtk+ Sequencer
Exec=/opt/bin/gsequencer
Comment=Tree based audio processing engine released under the terms of the GNU GPLv3+. It uses extensively threads, supporting LADSPA, DSSI and Lv2 plugin format.
Icon=gsequencer
Type=Application
Categories=Audio;" >> /home/$USER/.local/share/applications/$APP.desktop;

wget https://raw.githubusercontent.com/ivan-hc/AppMan/main/applications/$APP/$APP.svg;
mv ./$APP.svg /home/$USER/.local/share/icons/;

echo "";
echo " Advanced Gtk+ Sequencer is provided by https://github.com/gsequencer ";
echo "";

rm -R -f /opt/bin/tmp /opt/bin/$APP-installer /opt/bin/$APP-updater
