#!/bin/sh

APP=streamlink

cd /opt/bin;
mkdir tmp;
cd ./tmp;
wget https://github.com/$(wget https://github.com/streamlink/streamlink-appimage/releases/latest -O - | egrep '/.*/.*/.*x86_64.AppImage' -o);
cd ..;
mv ./tmp/*mage ./$APP;
chmod a+x /opt/bin/$APP;

echo "";
echo " This AppImage is provided by https://github.com/streamlink ";
echo "";

rm -R -f /opt/bin/tmp /opt/bin/$APP-installer /opt/bin/$APP-updater
