#!/bin/sh

APP=supertux2

cd /opt/bin;
mkdir tmp;
cd ./tmp;
wget https://github.com/$(wget https://github.com/SuperTux/supertux/releases/latest -O - | egrep '/.*/.*/.*AppImage' -o);
cd ..;
mv ./tmp/*mage ./$APP;
chmod a+x /opt/bin/$APP;

rm /home/$USER/.local/share/applications/$APP.desktop;
echo "[Desktop Entry]
Type=Application
Version=1.0
Name=SuperTux 2
Name[en]=SuperTux 2
GenericName=Platform Game
GenericName[en]=Platform Game
GenericName[ca]=Videojoc de Plataformes
GenericName[cs]=Plošinová hra
GenericName[da]=Platformspil
GenericName[de]=Jump ’n’ Run
GenericName[es]=Juego de Plataformas
GenericName[fr]=Jeu de Plate-forme
GenericName[hu]=Egy oldalnézeti játék
GenericName[it]=Videogioco a Piattaforme
GenericName[lt]=Platformos žaidimas
GenericName[nb]=Plattformspill
GenericName[nn]=Plattformspel
GenericName[nl]=Platformspel
GenericName[pt]=Jogo de Plataformas
GenericName[pt_BR]=Jogo de Plataforma
GenericName[ru]=Платформер
GenericName[fi]=Tasohyppely
GenericName[sv]=Plattformsspel
GenericName[tr]=Platform Oyunları
Comment=Play a classic 2D platform game
Comment[en]=Play a classic 2D platform game
Comment[de]=Ein klassisches Jump&Run Spiel
Comment[cs]=Plošinovka inspirovaná SuperMariem s tučňákem Tuxem v hlavní roli
Comment[fi]=Ohjaa pingviiniä perinteisessä tasohyppelyssä
Comment[lt]=Klasikinis 2D platformos žaidimas
Comment[nb]=Et klassisk todimensjonalt plattformspill.
Comment[nn]=Eit klassisk todimensjonalt plattformspel.
Comment[sv]=Ett klassiskt tvådimensionellt plattformsspel
Comment[pt]=Joga este clássico de plataformas 2D
Comment[pt_BR]=Encarne o pinguin Tux neste jogo inspirado em clássicos de Pular&Correr
Comment[hu]=Egy klasszikus 2D-s oldalnézeti játék
Icon=supertux2
Exec=/opt/bin/supertux2
Terminal=false
StartupNotify=false
Categories=Game;ArcadeGame;
Keywords=game;arcade;platform;" >> /home/$USER/.local/share/applications/$APP.desktop;

wget https://raw.githubusercontent.com/ivan-hc/AppMan/main/applications/$APP/$APP.svg;
mv ./$APP.svg /home/$USER/.local/share/icons/;

echo "";
echo " SuperTux is provided by https://www.supertux.org ";
echo "";

rm -R -f /opt/bin/tmp /opt/bin/$APP-installer /opt/bin/$APP-updater
