#!/bin/sh

cd /opt/bin;
mkdir /opt/bin/tmp;
cd ./tmp;

wget --user-agent="X11; Linux x86_64;" https://sourceforge.net/projects/avidemux/files/latest/download;
mv ./download ./avidemux.AppImage;

cd ..;

mv /opt/bin/tmp/*AppImage /opt/bin/avidemux; 
chmod a+x /opt/bin/avidemux;
rm /home/$USER/.local/share/applications/avidemux.desktop;
echo "[Desktop Entry]
Name=Avidemux
GenericName=Video Editor
Comment=Multiplatform video editor
Exec=/opt/bin/avidemux %U
Icon=avidemux
Terminal=false
Type=Application
Categories=AudioVideo;AudioVideoEditing;Video;
MimeType=video/mpeg;video/x-mpeg;video/mp4;video/x-m4v;video/quicktime;video/3gp;video/mkv;video/x-matroska;video/webm;video/flv;video/x-flv;video/dv;video/x-msvideo;video/x-ms-wmv;video/x-ms-asf;video/x-anim;" >> /home/$USER/.local/share/applications/avidemux.desktop;
wget https://raw.githubusercontent.com/ivan-hc/AppMan/main/applications/avidemux/avidemux.svg;
mv ./avidemux.svg /home/$USER/.local/share/icons/;
echo "";
echo "   Avidemux AppImage is provided by http://avidemux.sourceforge.net";
echo "";
rm -R /opt/bin/avidemux-installer /opt/bin/tmp
