#!/bin/sh

cd /opt/bin;
mkdir tmp;
cd ./tmp;
pkg2appimage Chromium;
ARCH=x86_64 appimagetool -n ./Chromium/Chromium.AppDir;

cd ..;

mv /opt/bin/tmp/*AppImage /opt/bin/chromium-dev; 
chmod a+x /opt/bin/chromium-dev;

echo "[Desktop Entry]
Type=Application
Name=Chromium Development Edition
Icon=chromium-dev
Exec=/opt/bin/chromium-dev %u
Categories=GNOME;GTK;Network;WebBrowser;
MimeType=text/html;text/xml;application/xhtml+xml;application/xml;application/rss+xml;application/rdf+xml;image/gif;image/jpeg;image/png;x-scheme-handler/http;x-scheme-handler/https;x-scheme-handler/ftp;x-scheme-handler/chrome;video/webm;application/x-xpinstall;
StartupNotify=true" >> /home/$USER/.local/share/applications/chromium-dev.desktop;
wget https://raw.githubusercontent.com/ivan-hc/AppMan/main/applications/chromium-dev/chromium-dev.svg;
mv ./chromium-dev.svg /home/$USER/.local/share/icons/;
echo "";
echo " This is the Unofficial AppImage for Chromium Development Edition ";
echo "                  'appman -i chromium-dev' ";
echo "   to install a new and more updated version, when available ";
echo "";
rm -R /opt/bin/chromium-dev-installer /opt/bin/tmp

