#!/bin/sh

APP=rssguard

cd /opt/bin;
mkdir tmp;
cd ./tmp;
wget https://github.com/$(wget https://github.com/martinrotter/rssguard/releases/latest -O - | egrep '/.*/.*/.*nowebengine-linux64.AppImage' -o);
cd ..;
mv ./tmp/*mage ./$APP;
chmod a+x /opt/bin/$APP;

rm /home/$USER/.local/share/applications/$APP.desktop;
echo "[Desktop Entry]
Name=RSS Guard
Exec=/opt/bin/rssguard
Comment=RSS Guard is simple feed reader which supports RSS/ATOM/JSON and many web-based feed services.
Icon=rssguard
Type=Application
Categories=Utility;" >> /home/$USER/.local/share/applications/$APP.desktop;

wget https://raw.githubusercontent.com/ivan-hc/AppMan/main/applications/$APP/$APP.svg;
mv ./$APP.svg /home/$USER/.local/share/icons/;

echo "";
echo " This AppImage is provided by https://github.com/martinrotter/rssguard ";
echo "";

rm -R -f /opt/bin/tmp /opt/bin/$APP-installer /opt/bin/$APP-updater
