#!/bin/sh

APP=knavalbattle

cd /opt/bin;
mkdir tmp;
cd ./tmp;

echo "app: knavalbattle
binpatch: true

ingredients:
  dist: stable
  sources:
    - deb http://ftp.us.debian.org/debian/ stable main contrib non-free" >> recipe.yml

pkg2appimage ./recipe.yml;


ARCH=x86_64 appimagetool -n ./$APP/$APP.AppDir;

cd ..;

mv /opt/bin/tmp/*AppImage /opt/bin/$APP; 
chmod a+x /opt/bin/$APP;

rm /home/$USER/.local/share/applications/$APP.desktop;
echo "[Desktop Entry]
Name=Naval Battle
Name[bs]=Pomorska bitka
Name[ca]=Batalla naval
Name[ca@valencia]=Batalla naval
Name[da]=Naval Battle
Name[de]=Naval Battle
Name[el]=Ναυμαχία
Name[en_GB]=Naval Battle
Name[es]=Batalla Naval
Name[et]=Merelahing
Name[fi]=Meritaistelu
Name[fr]=Bataille navale
Name[ga]=Comhrac Cabhlaigh
Name[gl]=Batalla Naval
Name[hu]=Tengeri csata
Name[id]=Naval Battle
Name[it]=Battaglia navale
Name[kk]=Теңіз соғысы
Name[km]=ចម្បាំង​តាម​នាវា
Name[ko]=전함 대전
Name[lt]=Jūrų mūšis
Name[lv]=Naval Battle
Name[mr]=नाविक युद्ध
Name[nb]=Sjøslag
Name[nds]=Scheep versenken
Name[nl]=Naval Battle
Name[nn]=Sjøslag
Name[pl]=Bitwa Morska
Name[pt]=Batalha Naval
Name[pt_BR]=Batalha Naval
Name[ro]=Bătălie navală
Name[ru]=Naval Battle
Name[sk]=Námorná bitka
Name[sl]=Naval Battle
Name[sr]=Поморска битка
Name[sr@ijekavian]=Поморска битка
Name[sr@ijekavianlatin]=Pomorska bitka
Name[sr@latin]=Pomorska bitka
Name[sv]=Sänka fartyg
Name[tr]=Amiral Battı
Name[ug]=دېڭىز ئۇرۇشى
Name[uk]=Морський бій
Name[x-test]=xxNaval Battlexx
Name[zh_CN]=Naval Battle
Name[zh_TW]=海上戰爭
Exec=/opt/bin/knavalbattle -qwindowtitle %c %U
MimeType=inode/vnd.kde.service.knavalbattle;
Icon=knavalbattle
Type=Application
X-DocPath=knavalbattle/index.html
GenericName=Ship Sinking Game
GenericName[bs]=Igra potapanja brodova
GenericName[ca]=Joc de tocar i enfonsar vaixells
GenericName[ca@valencia]=Joc de tocar i enfonsar vaixells
GenericName[da]=Sænke slagskibe
GenericName[de]=Schiffe versenken
GenericName[el]=Παιχνίδι βύθισης πλοίων
GenericName[en_GB]=Ship Sinking Game
GenericName[es]=Juego de hundir barcos
GenericName[et]=Laevade pommitamise mäng
GenericName[fi]=Laivanupotuspeli
GenericName[fr]=Jeu de touché-coulé
GenericName[ga]=Cluiche Comhraic Chabhlaigh
GenericName[gl]=Xogo de afundir barcos.
GenericName[hu]=Hajóelsüllyesztő játék
GenericName[id]=Permainan Kapal Selam
GenericName[it]=Gioco di affondamento navi
GenericName[kk]=Теңіздегі соғыс ойны
GenericName[km]=ល្បែង​ពន្លិច​កប៉ាល់
GenericName[ko]=전함 침몰 게임
GenericName[lt]=Laivų skandinimo žaidimas
GenericName[lv]=Kuģu gremdēšanas spēle
GenericName[mr]=नाव बुडविण्याचा खेळ
GenericName[nb]=Spill om å senke skip
GenericName[nds]=Scheep versenken
GenericName[nl]=Het spel voor het laten zinken van schepen
GenericName[nn]=Spel om å senka slagskip
GenericName[pl]=Gra w zatapianie statków
GenericName[pt]=Jogo para Afundar Navios
GenericName[pt_BR]=Jogo para afundar navios
GenericName[ro]=Joc de scufundat corăbii
GenericName[ru]=Морской бой
GenericName[sk]=Potápanie lodí
GenericName[sl]=Igra potapljanja ladjic
GenericName[sr]=Игра потапања бродова
GenericName[sr@ijekavian]=Игра потапања бродова
GenericName[sr@ijekavianlatin]=Igra potapanja brodova
GenericName[sr@latin]=Igra potapanja brodova
GenericName[sv]=Sänka fartygsspel
GenericName[tr]=Gemi Batırma Oyunu
GenericName[ug]=كېمە چۆكتۈرۈش ئويۇنى
GenericName[uk]=Гра у битву кораблів
GenericName[x-test]=xxShip Sinking Gamexx
GenericName[zh_CN]=击沉舰船游戏
GenericName[zh_TW]=擊沉船隻的遊戲
Terminal=false
X-DBUS-StartupType=Multi
Categories=Qt;KDE;Game;StrategyGame;
X-DBUS-ServiceName=org.kde.knavalbattle" >> /home/$USER/.local/share/applications/$APP.desktop;

wget https://raw.githubusercontent.com/ivan-hc/AppMan/main/applications/$APP/$APP.svg;
mv ./$APP.svg /home/$USER/.local/share/icons/;

echo "";
echo "   This AppImage was created from Debian Stable using";
echo "";
echo "       https://github.com/AppImage/pkg2appimage ";
echo "";

rm -R -f /opt/bin/tmp /opt/bin/$APP-installer /opt/bin/$APP-updater
