#!/bin/sh

APP=vidcutter

cd /opt/bin;
mkdir tmp;
cd ./tmp;

v=$(wget -q https://api.github.com/repos/ozmartian/vidcutter/releases/latest -O - | grep -E tag_name | awk -F '[""]' '{print $4}')
wget https://github.com/ozmartian/vidcutter/releases/download/$v/VidCutter-$v-x86_64.AppImage;

cd ..;
mv ./tmp/*mage ./$APP;
chmod a+x /opt/bin/$APP;

rm /home/$USER/.local/share/applications/$APP.desktop;
echo "[Desktop Entry]
Name=VidCutter
GenericName=Media Cutter + Joiner
X-GNOME-FullName=VidCutter
Comment=the simplest + fastest video cutter & joiner
Exec=/opt/bin/vidcutter %f
Terminal=false
Type=Application
Icon=vidcutter
Categories=Qt;KDE;Video;AudioVideo;AudioVideoEditing;
Keywords=editing;video;audio;ffmpeg;qt;python;pyqt;mpv;
MimeType=application/x-vidcutter;video/x-msvideo;video/x-ms-wmv;video/x-matroska-3d;video/x-matroska;video/x-flv;video/webm;video/quicktime;video/mpeg;video/mp4;video/3gpp2;video/3gpp;video/mp2t;
StartupNotify=true" >> /home/$USER/.local/share/applications/$APP.desktop;

wget https://raw.githubusercontent.com/ivan-hc/AppMan/main/applications/$APP/$APP.svg;
mv ./$APP.svg /home/$USER/.local/share/icons/;

echo "";
echo " VidCutter is provided by https://github.com/ozmartian/vidcutter";
echo "";

rm -R /opt/bin/tmp /opt/bin/$APP-installer
