#!/bin/sh

cd /opt/bin;
mkdir tmp;
cd ./tmp;
wget -r -A .AppImage -nd https://github.com/mmtrt/WINE_AppImage/releases/tag/continuous-stable;
cd ..;
mv ./tmp/wine*AppImage ./wine-stable;
chmod a+x /opt/bin/wine-stable;
echo "";
echo " WINE AppImage is provided by https://github.com/mmtrt ";
echo "";
rm -R /opt/bin/tmp /opt/bin/wine-stable-installer
