#!/bin/sh

cd /opt/bin;
wget https://raw.githubusercontent.com/ivan-hc/AppMan/main/applications/libreoffice-still/libreoffice-still-installer;
chmod a+x /opt/bin/libreoffice-still-installer;
exec /opt/bin/libreoffice-still-installer;
