#!/bin/sh

cd /opt/bin;
mv ./appimagetool ./appimagetool-zs-old
wget https://github.com/ivan-hc/AppMan/raw/main/applications/appimagetool/appimagetool;
chmod a+x /opt/bin/appimagetool;
#sudo ln -s /opt/bin/appimagetool /usr/bin/appimagetool;
rm /opt/bin/appimagetool-installer
