#!/bin/sh

APP=hexoeditor

cd /opt/bin;
mkdir tmp;
cd ./tmp;
wget https://github.com/$(wget https://github.com/zhuzhuyule/HexoEditor/releases/latest -O - | egrep '/.*/.*/.*x64.AppImage' -o);
cd ..;
mv ./tmp/*mage ./$APP;
chmod a+x /opt/bin/$APP;

rm /home/$USER/.local/share/applications/$APP.desktop;
echo "[Desktop Entry]
Name=HexoEditor
Comment=This is markdown editor for Hexo.
Exec=/opt/bin/hexoeditor
Terminal=false
Type=Application
Icon=hexoeditor
Categories=Utility;" >> /home/$USER/.local/share/applications/$APP.desktop;

wget https://raw.githubusercontent.com/ivan-hc/AppMan/main/applications/$APP/$APP.svg;
mv ./$APP.svg /home/$USER/.local/share/icons/;

echo "";
echo "        HexoEditor is provided by";
echo "";
echo "  https://github.com/zhuzhuyule/HexoEditor ";
echo "";

rm -R /opt/bin/tmp /opt/bin/$APP-installer
