#!/bin/sh

APP=zoom

cd /opt/bin;
mkdir tmp;
cd ./tmp;


pkg2appimage Zoom;

ARCH=x86_64 appimagetool -n ./Zoom/Zoom.AppDir;

cd ..;

mv /opt/bin/tmp/*AppImage /opt/bin/$APP; 
chmod a+x /opt/bin/$APP;

rm >> /home/$USER/.local/share/applications/$APP.desktop;
echo "[Desktop Entry]
Name=Zoom
Comment=Zoom Video Conference
Exec=/opt/bin/zoom %U
Icon=Zoom
Terminal=false
Type=Application
Encoding=UTF-8
Categories=Network;Application;
StartupWMClass=zoom
MimeType=x-scheme-handler/zoommtg;x-scheme-handler/zoomus;x-scheme-handler/tel;x-scheme-handler/callto;x-scheme-handler/zoomphonecall;application/x-zoom
X-KDE-Protocols=zoommtg;zoomus;tel;callto;zoomphonecall;
Name[en_US]=Zoom" >> /home/$USER/.local/share/applications/$APP.desktop;
wget https://raw.githubusercontent.com/ivan-hc/AppMan/main/applications/$APP/$APP.svg;
mv ./$APP.svg /home/$USER/.local/share/icons/;

echo "";
echo "      This AppImage is provided by";
echo " https://github.com/AppImage/pkg2appimage ";
echo "";

rm -R -f /opt/bin/tmp /opt/bin/$APP-installer /opt/bin/$APP-updater
