#!/bin/sh

APP=altus

cd /opt/bin;
mkdir tmp;
cd ./tmp;
wget https://github.com/$(wget https://github.com/amanharwara/altus/releases/latest -O - | egrep '/.*/.*/.*AppImage' -o);
cd ..;
mv ./tmp/*mage ./$APP;
chmod a+x /opt/bin/$APP;

rm /home/$USER/.local/share/applications/$APP.desktop;
echo "[Desktop Entry]
Name=Altus
Exec=/opt/bin/altus --no-sandbox %U
Terminal=false
Type=Application
Icon=altus
StartupWMClass=Altus
Comment=Desktop client for WhatsApp Web with themes & multiple account support.
MimeType=x-scheme-handler/whatsapp;
Categories=Chat;" >> /home/$USER/.local/share/applications/$APP.desktop;

wget https://raw.githubusercontent.com/ivan-hc/AppMan/main/applications/$APP/$APP.svg;
mv ./$APP.svg /home/$USER/.local/share/icons/;

echo "";
echo " Altus WhatsApp Web Client is provided by";
echo "";
echo "   https://github.com/amanharwara/altus";
echo "";

rm -R -f /opt/bin/tmp /opt/bin/$APP-installer /opt/bin/$APP-updater
