#!/bin/sh

APP=ventoy

cd /opt/bin;
mkdir tmp;
cd ./tmp;

wget https://github.com/$(wget https://github.com/ventoy/Ventoy/releases/latest -O - | egrep '/.*/.*/.*linux.tar.gz' -o);
tar xf ./*.tar.gz;
rm ./*tar.gz;
cd ..;
mv ./tmp/* ./.$APP;

rm /opt/bin/$APP;
echo '#!/bin/sh
cd /opt/bin/.ventoy;
sudo ./VentoyGUI.x86_64' >> /opt/bin/$APP;
chmod a+x /opt/bin/$APP;

rm /home/$USER/.local/share/applications/$APP.desktop;
echo "[Desktop Entry]
Name=Ventoy
Comment=Open source tool to create bootable USB drive for ISO/WIM/IMG/VHD(x)/EFI files. 
Exec=/opt/bin/.ventoy/VentoyGUI.x86_64
Icon=ventoy
Type=Application
Categories=System;" >> /home/$USER/.local/share/applications/$APP.desktop;

wget https://raw.githubusercontent.com/ivan-hc/AppMan/main/applications/$APP/$APP.svg;
mv ./$APP.svg /home/$USER/.local/share/icons/;
echo "";

echo "   Ventoy is provided by https://www.ventoy.net ";

echo "";
rm -R -f /opt/bin/tmp /opt/bin/$APP-installer /opt/bin/$APP-updater
