#!/bin/sh

cd /opt/bin;
mkdir tmp;
cd ./tmp;
wget https://nodejs.org/dist/v16.9.1/node-v16.9.1-linux-x64.tar.gz;
tar fx node-v16.9.1-linux-x64.tar.gz
rm -R /opt/bin/.nodejs;
mv ./node-v16.9.1-linux-x64 /opt/bin/nodejs;

echo '#!/bin/sh
echo "";
echo " Script to create symbolic links for programs installed with NodeJS to /opt/bin";
echo "";
echo "  Please wait...";
sleep 2;
ln -s /opt/bin/nodejs/bin/* /opt/bin/ 2> /dev/null;
echo "";
echo "    ...done, now you can use all programs installed with node / npm normally";
echo "";
sleep 1;
echo "  NOTE: run this command after every program installed with node / npm"; 
echo "";' >> /opt/bin/nodejs/bin/npm-programs;
chmod a+x /opt/bin/nodejs/bin/npm-programs;

ln -s /opt/bin/nodejs/bin/* /opt/bin/;

cd ..;

echo "";
echo " NodeJS is provided by https://nodejs.org ";
echo "";

rm -R /opt/bin/tmp /opt/bin/$APP-installer
