#!/bin/sh

APP=nodejs

cd /opt/bin;
mkdir tmp;
cd ./tmp;
wget wget -r -erobots=off -l1 -np -A node-*-linux-x64.tar.gz  -nd https://nodejs.org/dist/latest/;
tar fx *.tar.gz
rm -R /opt/bin/.nodejs;
mv ./node-*-linux-x64 /opt/bin/.nodejs;

rm /opt/bin/nodejs;
echo '#!/bin/sh
echo "";
echo " NodeJS programs are in /opt/bin/.nodejs/bin/, use ./ before each command."
echo "";
echo " For example:";
echo "";
echo " ./program <options> [arguments]";
echo "";
cd /opt/bin/.nodejs/bin;
exec bash;' >> /opt/bin/nodejs;
chmod a+x /opt/bin/nodejs;
cd ..;

ln -s /opt/bin/.nodejs/bin/* /opt/bin/;

rm /home/$USER/.local/share/applications/$APP.desktop;
echo "[Desktop Entry]
Name=NodeJS (Terminal)
Comment=A JavaScript runtime built on Chrome's V8 JavaScript engine.
Exec=exo-open --working-directory /opt/bin/.nodejs/bin --launch TerminalEmulator
Icon=nodejs
Type=Application
Categories=Development;" >> /home/$USER/.local/share/applications/$APP.desktop;

wget https://raw.githubusercontent.com/ivan-hc/AppMan/main/applications/$APP/$APP.svg;
mv ./$APP.svg /home/$USER/.local/share/icons/;

echo "";
echo " NodeJS is provided by https://nodejs.org ";
echo "";

rm -R /opt/bin/tmp /opt/bin/*-installer
