#!/bin/sh

APP=walc

cd /opt/bin;
mkdir tmp;
cd ./tmp;

v=$(wget -q https://api.github.com/repos/WAClient/WALC/releases/latest -O - | grep -E tag_name | awk -F '[""]' '{print $4}')
wget https://github.com/WAClient/WALC/releases/download/$v/walc.AppImage;

cd ..;
mv ./tmp/*mage ./$APP;
chmod a+x /opt/bin/$APP;

rm /home/$USER/.local/share/applications/$APP.desktop;
echo "[Desktop Entry]
Name=WALC
Exec=/opt/bin/walc --no-sandbox %U
Terminal=false
Type=Application
Icon=walc
StartupWMClass=WALC
Comment=An unofficial WhatsApp Desktop client for Linux. For official client use https://web.whatsapp.com as the official desktop client for Linux is not available.
Categories=Social;Network;" >> /home/$USER/.local/share/applications/$APP.desktop;

wget https://raw.githubusercontent.com/ivan-hc/AppMan/main/applications/$APP/$APP.svg;
mv ./$APP.svg /home/$USER/.local/share/icons/;

echo "";
echo "   WALC - WhatsApp Linux Client (unofficial)";
echo "  is provided by https://github.com/WAClient";
echo "";

rm -R -f /opt/bin/tmp /opt/bin/$APP-installer /opt/bin/$APP-updater
