#!/bin/sh

APP=spacewars

cd /opt/bin;
mkdir tmp;
cd ./tmp;
wget https://github.com/$(wget https://github.com/spotzero/spacewars/releases/latest -O - | egrep '/.*/.*/.*AppImage' -o);
cd ..;
mv ./tmp/*mage ./$APP;
chmod a+x /opt/bin/$APP;

rm /home/$USER/.local/share/applications/$APP.desktop;
echo "[Desktop Entry]
Name=Spacewars
Exec=/opt/bin/spacewars
Type=Application
Comment=A re-imagining of the classic game Spacewar! in Rust using the Amethyst game engine. 
Categories=Game;
Icon=spacewars" >> /home/$USER/.local/share/applications/$APP.desktop;

wget https://raw.githubusercontent.com/ivan-hc/AppMan/main/applications/$APP/$APP.svg;
mv ./$APP.svg /home/$USER/.local/share/icons/;

echo "";
echo " Spacewars is provided by https://github.com/spotzero/spacewars ";
echo "";

rm -R -f /opt/bin/tmp /opt/bin/$APP-installer /opt/bin/$APP-updater
