#!/bin/sh

# $APP must use lowercase letters, because it is a "command".
# The same name is used for the icon SAMPLE.svg and the file about-SAMPLE in the main folder of the app.
APP=SAMPLE

# Entering in /opt/bin will be created a /tmp folder in which all the operations will be performed
cd /opt/bin;
mkdir tmp;
cd ./tmp;

# Download and extract the TAR.* archive this way
# To download more archives you may be interested in merging this tool https://github.com/ivan-hc/Arch-Deployer in this script
wget LINK;
tar xf ./*.tar.zst;
# Create the AppDir
mkdir $APP.AppDir;
# Move the /usr folder in AppDir... and if available, move also other folders (ie /etc, /var, /lib, /lib64, etcetera, this way:
mv ./usr ./$APP.AppDir;

# Now copy the launcher in AppDir
cp ./$APP.AppDir/usr/share/applications/*.desktop ./$APP.AppDir;
# And copy the icon (it may be in /usr/icons/... or /usr/pixmaps, check it before
# and write a command like this in the example, based in the path of the icon
cp ./$APP.AppDir/usr/share/icons/hicolor/128x128/apps/*.png ./$APP.AppDir;

# Now you should manually create an AppRun script in the AppDir, replace "YOUR-APPRUN" with the content of your AppRun
# More instructions on how to create una AppRun are available at https://github.com/AppImageCrafters/AppRun
echo 'YOUR-APPRUN' >> /opt/bin/tmp/$APP.AppDir/AppRun;
chmod a+x /opt/bin/tmp/$APP.AppDir/AppRun;

# Run appimagetool on the AppDir
ARCH=x86_64 appimagetool -n ./$APP.AppDir;

# Renaming the created AppImage to $APP
cd ..;
mv /opt/bin/tmp/*AppImage /opt/bin/$APP; 
chmod a+x /opt/bin/$APP;


# Creating a LAUNCHER (the old one will be removed if already exists)
rm /home/$USER/.local/share/applications/$APP.desktop;
# This is an example of launcher:
# 1) APPNAME can be different from $APP with Capital letters if needed
# 2) $APP in Exec must be always placed in /opt/bin
# 3) COMMENT is the description of the app (optional)
# 4) Choose a category at the end to show the app into a category of the menu
echo "[Desktop Entry]
Name=APPNAME
Exec=/opt/bin/SAMPLE 
Comment=COMMENT
Icon=SAMPLE
Type=Application
Categories=Utility;System;Office;Game;Network;Development;Education;AudioVideo;Graphics;" >> /home/$USER/.local/share/applications/$APP.desktop;

# The icon of the app will be downloaded from this repository
wget https://raw.githubusercontent.com/ivan-hc/AppMan/main/applications/$APP/$APP.svg;
mv ./$APP.svg /home/$USER/.local/share/icons/;

# Replace LINK with the source of this app
echo "";
echo " This AppImage is provided by LINK ";
echo "";

# The installer script, the /tmp folder and an eventual "updater" file will be removed
rm -R -f /opt/bin/tmp /opt/bin/$APP-installer /opt/bin/$APP-updater
