#!/bin/sh

APP=knetwalk

cd /opt/bin;
mkdir tmp;
cd ./tmp;

echo "app: knetwalk
binpatch: true

ingredients:
  dist: stable
  sources:
    - deb http://ftp.us.debian.org/debian/ stable main contrib non-free" >> recipe.yml

pkg2appimage ./recipe.yml;


ARCH=x86_64 appimagetool -n ./$APP/$APP.AppDir;

cd ..;

mv /opt/bin/tmp/*AppImage /opt/bin/$APP; 
chmod a+x /opt/bin/$APP;

rm /home/$USER/.local/share/applications/$APP.desktop;
echo "[Desktop Entry]
Type=Application
Exec=/opt/bin/knetwalk -qwindowtitle %c
X-DocPath=knetwalk/index.html
Name=KNetWalk
Name[bs]=KNetWalk
Name[ca]=KNetWalk
Name[ca@valencia]=KNetWalk
Name[cs]=KNetWalk
Name[da]=KNetWalk
Name[de]=KNetWalk
Name[el]=KNetWalk
Name[en_GB]=KNetWalk
Name[es]=KNetWalk
Name[et]=KNetWalk
Name[eu]=KNetWalk
Name[fa]=گشت شبکه‌
Name[fi]=KNetWalk
Name[fr]=KNetWalk
Name[ga]=KNetWalk
Name[gl]=KNetWalk
Name[hi]=केनेटवाक
Name[hne]=के-नेट-वाक
Name[hu]=KNetWalk
Name[id]=KNetWalk
Name[is]=KNetWalk
Name[it]=KNetWalk
Name[ja]=KNetWalk
Name[kk]=KNetWalk
Name[km]=KNetWalk
Name[ko]=KNetWalk
Name[lt]=KNetWalk
Name[lv]=KNetWalk
Name[mr]=के-नेट-वॉक
Name[nb]=KNetWalk
Name[nds]=KNetWalk
Name[nl]=KNetWalk
Name[nn]=KNettvandrar
Name[pl]=KNetWalk
Name[pt]=KNetWalk
Name[pt_BR]=KNetWalk
Name[ro]=KNetWalk
Name[ru]=KNetWalk
Name[sk]=KNetWalk
Name[sl]=KNetWalk
Name[sq]=KNetWalk
Name[sr]=К‑мрежоход
Name[sr@ijekavian]=К‑мрежоход
Name[sr@ijekavianlatin]=K‑mrežohod
Name[sr@latin]=K‑mrežohod
Name[sv]=Knetwalk
Name[te]=కెనెట్ వాక్
Name[tr]=KNetWalk
Name[ug]=KNetWalk
Name[uk]=KNetWalk
Name[wa]=KNetWalk
Name[x-test]=xxKNetWalkxx
Name[zh_CN]=KNetWalk
Name[zh_TW]=KNetWalk
GenericName=Network Construction Game
GenericName[bs]=Igra gradnje mreže
GenericName[ca]=Joc de construcció de xarxes
GenericName[ca@valencia]=Joc de construcció de xarxes
GenericName[cs]=Hra s vytvářením sítě
GenericName[da]=Spil om netværksopbygning
GenericName[de]=Netzwerke aufbauen
GenericName[el]=Παιχνίδι δημιουργίας δικτύου
GenericName[en_GB]=Network Construction Game
GenericName[es]=Juego de construcción de redes
GenericName[et]=Võrgu loomise mäng
GenericName[eu]=Sarea eraikitzeko jokoa
GenericName[fa]=بازی ساخت شبکه
GenericName[fi]=Verkonrakennuspeli
GenericName[fr]=Jeu de construction de réseau
GenericName[ga]=Cluiche Tógála Líonra
GenericName[gl]=Xogo de construción de redes
GenericName[hi]=नेटवर्क कंस्ट्रक्शन का खेल
GenericName[hne]=नेटवर्क कंस्ट्रक्सन वाले खेल
GenericName[hu]=Hálózatépítő játék
GenericName[id]=Permainan Kontruksi Jaringan
GenericName[it]=Gioco di costruzione di reti
GenericName[ja]=ネットワーク構築ゲーム
GenericName[kk]=Желі торын құру ойыны
GenericName[km]=ល្បែង​តភ្ជាប់​បណ្ដាញ
GenericName[ko]=네트워크 건설 게임
GenericName[lt]=Tinklo konstravimo žaidimas
GenericName[lv]=Tīkla būvēšanas spēle
GenericName[mr]=संजाळ बांधण्याचा खेळ
GenericName[nb]=Bygg opp nettverk
GenericName[nds]=Nettwark-Buuspeel
GenericName[nl]=Netwerkconstructiespel
GenericName[nn]=Bygg opp nettverk
GenericName[pl]=Gra w konstrukcję sieci
GenericName[pt]=Jogo de Construção de Redes
GenericName[pt_BR]=Jogo de construção de uma rede de computadores
GenericName[ro]=Joc de construire a rețelei
GenericName[ru]=Игра в создание сетей
GenericName[sk]=Hra s budovaním siete
GenericName[sl]=Igra gradnje omrežja
GenericName[sq]=Lojë Për Ndërtimin e Rrjetit
GenericName[sr]=Игра конструисања мреже
GenericName[sr@ijekavian]=Игра конструисања мреже
GenericName[sr@ijekavianlatin]=Igra konstruisanja mreže
GenericName[sr@latin]=Igra konstruisanja mreže
GenericName[sv]=Nätverkskonstruktion
GenericName[tr]=Ağ Yapılandırma Oyunu
GenericName[ug]=تور قۇرۇلۇشى ئويۇنى
GenericName[uk]=Гра з побудови мереж
GenericName[wa]=Djeu d' costrujhaedje del rantoele
GenericName[x-test]=xxNetwork Construction Gamexx
GenericName[zh_CN]=网络建设游戏
GenericName[zh_TW]=網路建構遊戲
Comment=Strategy game
Comment[ca]=Joc d'estratègia
Comment[ca@valencia]=Joc d'estratègia
Comment[cs]=Strategická hra
Comment[da]=Strategispil
Comment[de]=Strategiespiel
Comment[el]=Παιχνίδι στρατηγικής
Comment[en_GB]=Strategy game
Comment[es]=Juego de estrategia
Comment[et]=Strateegiamäng
Comment[fi]=Strategiapeli
Comment[fr]=Jeu de stratégie
Comment[gl]=Xogo de estratexia.
Comment[id]=Permainan strategi
Comment[it]=Gioco di strategia
Comment[ko]=전략 게임
Comment[nl]=Strategiespel
Comment[nn]=Strategispel
Comment[pl]=Gra strategiczna
Comment[pt]=Jogo de estratégia
Comment[pt_BR]=Jogo de estratégia
Comment[ru]=Стратегическая галактическая игра
Comment[sk]=Strategická hra
Comment[sl]=Strateška igra
Comment[sr]=Стратешка игра
Comment[sr@ijekavian]=Стратешка игра
Comment[sr@ijekavianlatin]=Strateška igra
Comment[sr@latin]=Strateška igra
Comment[sv]=Strategispel
Comment[tr]=Strateji oyunu
Comment[uk]=Гра-стратегія
Comment[x-test]=xxStrategy gamexx
Comment[zh_CN]=策略游戏
Comment[zh_TW]=戰略遊戲
Terminal=false
Icon=knetwalk
StartupNotify=true
Categories=Qt;KDE;Game;StrategyGame;
X-DBUS-ServiceName=org.kde.knetwalk" >> /home/$USER/.local/share/applications/$APP.desktop;

wget https://raw.githubusercontent.com/ivan-hc/AppMan/main/applications/$APP/$APP.svg;
mv ./$APP.svg /home/$USER/.local/share/icons/;

echo "";
echo "   This AppImage was created from Debian Stable using";
echo "";
echo "       https://github.com/AppImage/pkg2appimage ";
echo "";

rm -R -f /opt/bin/tmp /opt/bin/$APP-installer /opt/bin/$APP-updater
