#!/bin/sh

APP=movie-monad

cd /opt/bin;
mkdir tmp;
cd ./tmp;

v=$(wget -q https://api.github.com/repos/lettier/movie-monad/releases/latest -O - | grep -E tag_name | awk -F '[""]' '{print $4}')
wget https://github.com/lettier/movie-monad/releases/download/$v/movie-monad-$v-x86_64.AppImage;

cd ..;
mv ./tmp/*mage ./$APP;
chmod a+x /opt/bin/$APP;

rm /home/$USER/.local/share/applications/$APP.desktop;
echo "[Desktop Entry]
Type=Application
Name=Movie Monad
GenericName=Video Player
Categories=AudioVideo;Audio;Video;Player;
Comment=Play Videos
Icon=com.lettier.movie-monad
Terminal=false
Exec=/opt/bin/movie-monad" >> /home/$USER/.local/share/applications/$APP.desktop;

wget https://raw.githubusercontent.com/ivan-hc/AppMan/main/applications/$APP/$APP.svg;
mv ./$APP.svg /home/$USER/.local/share/icons/;

echo "";
echo " Movie Monad is provided by https://github.com/lettier/movie-monad";
echo "";

rm -R /opt/bin/tmp /opt/bin/$APP-installer
