#!/bin/sh

APP=sigdigger

cd /opt/bin;
mkdir tmp;
cd ./tmp;
wget https://github.com/$(wget https://github.com/BatchDrake/SigDigger/releases/latest -O - | egrep '/.*/.*/.*full.AppImage' -o);
cd ..;
mv ./tmp/*mage ./$APP;
chmod a+x /opt/bin/$APP;

rm /home/$USER/.local/share/applications/$APP.desktop;
echo "[Desktop Entry]
Name=SigDigger
Exec=/opt/bin/sigdigger
Comment=Qt-based digital signal analyzer, using Suscan core and Sigutils DSP library.
Icon=sigdigger
Type=Application
Categories=Education; Science;" >> /home/$USER/.local/share/applications/$APP.desktop;

wget https://raw.githubusercontent.com/ivan-hc/AppMan/main/applications/$APP/$APP.svg;
mv ./$APP.svg /home/$USER/.local/share/icons/;

echo "";
echo " This AppImage is provided by https://github.com/BatchDrake/SigDigger ";
echo "";

rm -R -f /opt/bin/tmp /opt/bin/$APP-installer /opt/bin/$APP-updater
