#!/bin/sh

cd /opt/bin;
wget https://github.com/ivan-hc/AppMan/raw/main/applications/appimageupdate/appimageupdate;
chmod a+x /opt/bin/appimageupdate;
sudo ln -s /opt/bin/appimageupdate /usr/bin/appimageupdate;
