#!/bin/sh

APP=prime-world-editor

cd /opt/bin;
mkdir tmp;
cd ./tmp;
wget https://github.com/$(wget https://github.com/AxioDL/PrimeWorldEditor/releases/latest -O - | egrep '/.*/.*/.*AppImage' -o);
cd ..;
mv ./tmp/*mage ./$APP;
chmod a+x /opt/bin/$APP;

rm /home/$USER/.local/share/applications/$APP.desktop;
echo "[Desktop Entry]
Name=Prime World Editor
GenericName=Game Data Editor
Comment=Edit world assets from games by Retro Studios
Exec=env QT_QPA_PLATFORM=xcb /opt/bin/prime-world-editor
Icon=prime-world-editor
Terminal=false
Type=Application
Categories=Development;" >> /home/$USER/.local/share/applications/$APP.desktop;

wget https://raw.githubusercontent.com/ivan-hc/AppMan/main/applications/$APP/$APP.svg;
mv ./$APP.svg /home/$USER/.local/share/icons/;

echo "";
echo " Prime World Editor is provided by https://github.com/AxioDL/PrimeWorldEditor ";
echo "";

rm -R -f /opt/bin/tmp /opt/bin/$APP-installer /opt/bin/$APP-updater
