#!/bin/sh

APP=meta-grabber

cd /opt/bin;
mkdir tmp;
cd ./tmp;
wget https://github.com/$(wget https://github.com/andreaswilli/meta-grabber/releases/latest -O - | egrep '/.*/.*/.*AppImage' -o);
cd ..;
mv ./tmp/*mage ./$APP;
chmod a+x /opt/bin/$APP;

rm /home/$USER/.local/share/applications/$APP.desktop;
echo "[Desktop Entry]
Name=Meta Grabber
Exec=/opt/bin/meta-grabber
Comment=A tool to grab metadata for tv shows and rename files on your hard disk. 
Icon=meta-grabber
Type=Application
Categories=Utility;" >> /home/$USER/.local/share/applications/$APP.desktop;

wget https://raw.githubusercontent.com/ivan-hc/AppMan/main/applications/$APP/$APP.svg;
mv ./$APP.svg /home/$USER/.local/share/icons/;

echo "";
echo " This AppImage is provided by https://github.com/andreaswilli/meta-grabber ";
echo "";

rm -R -f /opt/bin/tmp /opt/bin/$APP-installer /opt/bin/$APP-updater
