#!/bin/sh

APP=castersoundboard

cd /opt/bin;
mkdir tmp;
cd ./tmp;
wget https://github.com/$(wget https://github.com/covarianttensor/CasterSoundboard/releases/tag/continuous -O - | egrep '/.*/.*/.*AppImage' -o);
cd ..;
mv ./tmp/*mage ./$APP;
chmod a+x /opt/bin/$APP;

rm /home/$USER/.local/share/applications/$APP.desktop;
echo "[Desktop Entry]
Version=1.0
Type=Application
Name=CasterSoundboard
Comment=A soundboard for hot-keying and playing back sounds
Icon=castersoundboard
Exec=/opt/bin/castersoundboard
NoDisplay=false
Categories=AudioVideo;
StartupNotify=false
Terminal=false" >> /home/$USER/.local/share/applications/$APP.desktop;

wget https://raw.githubusercontent.com/ivan-hc/AppMan/main/applications/$APP/$APP.svg;
mv ./$APP.svg /home/$USER/.local/share/icons/;

echo "";
echo "          CasterSoundboard is provided by";
echo "";
echo " https://github.com/covarianttensor/CasterSoundboard ";
echo "";

rm -R -f /opt/bin/tmp /opt/bin/$APP-installer /opt/bin/$APP-updater
