#!/bin/sh

APP=lskat

cd /opt/bin;
mkdir tmp;
cd ./tmp;

echo "app: lskat
binpatch: true

ingredients:
  dist: stable
  sources:
    - deb http://ftp.us.debian.org/debian/ stable main contrib non-free" >> recipe.yml

pkg2appimage ./recipe.yml;


ARCH=x86_64 appimagetool -n ./$APP/$APP.AppDir;

cd ..;

mv /opt/bin/tmp/*AppImage /opt/bin/$APP; 
chmod a+x /opt/bin/$APP;

rm /home/$USER/.local/share/applications/$APP.desktop;
echo "[Desktop Entry]
Name=LSkat
Name[be]=LSkat
Name[bs]=LSkat
Name[ca]=LSkat
Name[ca@valencia]=LSkat
Name[cs]=Poručík skat
Name[da]=LSkat
Name[de]=LSkat
Name[el]=LSkat
Name[en_GB]=LSkat
Name[eo]=LSkat
Name[es]=LSkat
Name[et]=LSkat
Name[eu]=LSkat
Name[fi]=LSkat
Name[fr]=LSkat
Name[ga]=LSkat
Name[gl]=LSkat
Name[hne]=एलएस-कैट
Name[hr]=LSkat
Name[hu]=LSkat
Name[id]=LSkat
Name[is]=LSkat
Name[it]=LSkat
Name[ja]=LSkat
Name[kk]= 
Name[km]=LSkat
Name[ko]=LSkat
Name[lt]=LSkat
Name[lv]=LSkat
Name[mr]=एल-स्केट
Name[nb]=LSkat
Name[nds]=LSkat
Name[ne]=एल स्क्याट
Name[nl]=LSkat
Name[nn]=Løytnant Skat
Name[pl]=LSkat
Name[pt]=LSkat
Name[pt_BR]=LSkat
Name[ru]=LSkat
Name[sk]=LSkat
Name[sl]=LSkat
Name[sr]=П‑скат
Name[sr@ijekavian]=П‑скат
Name[sr@ijekavianlatin]=P‑skat
Name[sr@latin]=P‑skat
Name[sv]=Officersskat
Name[te]=ఎల్ స్కెట్
Name[tr]=LSkat
Name[ug]=LSkat
Name[uk]=LSkat
Name[wa]=LSkat
Name[x-test]=xxLSkatxx
Name[zh_CN]=LSkat
Name[zh_TW]=LSkat
GenericName=Classic German Card Game
GenericName[ca]=Joc de cartes alemany clàssic
GenericName[ca@valencia]=Joc de cartes alemany clàssic
GenericName[cs]=Klasická německá karetní hra
GenericName[da]=Klassisk tysk kortspil
GenericName[de]=Klassisches deutsches Kartenspiel
GenericName[el]=Κλασικό γερμανικό παιχνίδι καρτών
GenericName[en_GB]=Classic German Card Game
GenericName[es]=Clásico juego de cartas alemán
GenericName[et]=Klassikaline Saksa kaardimäng
GenericName[eu]=Karta-joko aleman klasikoa
GenericName[fi]=Perinteinen saksalainen korttipeli
GenericName[fr]=Jeu de cartes classique allemand.
GenericName[it]=Classico gioco di carte tedesco
GenericName[ko]=고전 독일식 카드 게임
GenericName[nl]=Klassiek Duits kaartspel
GenericName[nn]=Klassisk tysk kortspel
GenericName[pl]=Klasyczna niemiecka gra karciana
GenericName[pt]=Jogo Clássico de Cartas Alemão
GenericName[pt_BR]=Jogo de cartas alemão clássico
GenericName[sk]=Klaskická nemecká kartová hra
GenericName[sl]=Klasična nemška igra s kartami
GenericName[sv]=Klassiskt tyskt kortspel
GenericName[uk]=Класична німецька карткова гра
GenericName[x-test]=xxClassic German Card Gamexx
Exec=/opt/bin/lskat
Icon=lskat
Terminal=false
Type=Application
X-DocPath=lskat/index.html
Categories=Qt;KDE;Game;CardGame;
X-DBUS-ServiceName=org.kde.lskat" >> /home/$USER/.local/share/applications/$APP.desktop;

wget https://raw.githubusercontent.com/ivan-hc/AppMan/main/applications/$APP/$APP.svg;
mv ./$APP.svg /home/$USER/.local/share/icons/;

echo "";
echo "   This AppImage was created from Debian Stable using";
echo "";
echo "       https://github.com/AppImage/pkg2appimage ";
echo "";

rm -R -f /opt/bin/tmp /opt/bin/$APP-installer /opt/bin/$APP-updater
