#!/bin/sh

APP=dropbox

cd /opt/bin;
mkdir tmp;
cd ./tmp;


wget -r -A dropbox-*-x86_64.pkg.tar.zst -nd https://aur.andontie.net/x86_64/;
tar xf ./*.tar.zst;
mkdir $APP.AppDir;
mv ./opt ./$APP.AppDir;
mv ./usr ./$APP.AppDir;
cp ./$APP.AppDir/usr/share/applications/*desktop ./$APP.AppDir;
cp ./$APP.AppDir/usr/share/pixmaps/*svg ./$APP.AppDir;

echo '#!/bin/sh
HERE="$(dirname "$(readlink -f "${0}")")"
export PATH="${HERE}/usr/lib/systemd/system/:${HERE}/usr/lib/systemd/user/:${HERE}/opt/dropbox/:${HERE}/opt/dropbox/resources/:${HERE}/opt/dropbox/plugins/platforms/:${HERE}/opt/dropbox/images/hicolor/16x16/status/:${HERE}/opt/dropbox/images/emblems/${PATH:+:$PATH}"
export LD_LIBRARY_PATH="${HERE}/opt/dropbox/:${HERE}/opt/dropbox/plugins/platforms/${LD_LIBRARY_PATH:+:$LD_LIBRARY_PATH}"
export XDG_DATA_DIRS="${HERE}/usr/share/${XDG_DATA_DIRS:+:$XDG_DATA_DIRS}"
EXEC="${HERE}/opt/dropbox/dropbox"
exec "${EXEC}"' >> ./$APP.AppDir/AppRun;
chmod a+x ./$APP.AppDir/AppRun;

ARCH=x86_64 appimagetool -n ./$APP.AppDir;

cd ..;
mv ./tmp/*mage ./$APP;
chmod a+x /opt/bin/$APP;

rm /home/$USER/.local/share/applications/$APP.desktop;
echo "[Desktop Entry]
Version=1.0
Type=Application
Name=Dropbox
Comment=A free service that lets you bring your photos, docs, and videos anywhere and share them easily.
Exec=/opt/bin/dropbox
Icon=dropbox
Terminal=false
StartupNotify=false
Categories=Network;" >> /home/$USER/.local/share/applications/$APP.desktop;


wget https://raw.githubusercontent.com/ivan-hc/AppMan/main/applications/$APP/$APP.svg;
mv ./$APP.svg /home/$USER/.local/share/icons/;
echo "";

echo "  This version of Dropbox comes from an Arch Linux repository";
echo "";
echo "                    'appman -i $APP' ";
echo "";
echo "   to install a new and more updated version, when available ";

echo "";
rm -R /opt/bin/$APP-installer /opt/bin/tmp
