#!/bin/sh

APP=SAMPLE

cd /opt/bin;
mkdir tmp;
cd ./tmp;


wget LINK;
ar x ./*.deb;
tar xf ./data.tar.xz;
mkdir $APP.AppDir;
mv ./usr ./$APP.AppDir;
cp ./$APP.AppDir/usr/share/applications/*.desktop ./$APP.AppDir;
cp ./$APP.AppDir/usr/share/icons/hicolor/128x128/apps/*.png ./$APP.AppDir;

echo 'YOUR-APPRUN' >> /opt/bin/tmp/$APP.AppDir/AppRun;
chmod a+x /opt/bin/tmp/$APP.AppDir/AppRun;

ARCH=x86_64 appimagetool -n ./$APP.AppDir;

cd ..;

mv /opt/bin/tmp/*AppImage /opt/bin/$APP; 
chmod a+x /opt/bin/$APP;
rm 
echo "LAUNCHER" >> /home/$USER/.local/share/applications/$APP.desktop;


wget https://raw.githubusercontent.com/ivan-hc/AppMan/main/applications/$APP/$APP.svg;
mv ./$APP.svg /home/$USER/.local/share/icons/;
echo "";

echo "          This version of SAMPLE comes from";
echo "                          LINK";
echo "                   'appman -i SAMPLE' ";
echo " to install a new and more updated version, when available ";

echo "";
rm -R /opt/bin/$APP-installer /opt/bin/tmp
