#!/bin/sh

APP=SAMPLE

cd /opt/bin;
mkdir tmp;
cd ./tmp;


wget LINK;
ar x ./*.deb;
tar xf ./data.tar.xz;
mv /opt/bin/tmp/YOUR-DEBIAN-PROGRAM /home/$USER/.local/share/$APP;
ln -s /home/$USER/.local/share/$APP/$APP /opt/bin/$APP;


echo "LAUNCHER" >> /home/$USER/.local/share/applications/google-chrome.desktop;


wget https://raw.githubusercontent.com/ivan-hc/AppMan/main/applications/$APP/$APP.svg;
mv ./$APP.svg /home/$USER/.local/share/icons/;
echo "";

echo "   This version of $APP comes from the official DEB ";
echo "         'appman -r $APP && appman -i $APP' ";
echo " to install a new and more updated version, when available ";

echo "";
rm -R /opt/bin/$APP-installer /opt/bin/tmp
