#!/bin/sh

APP=SAMPLE

cd /opt/bin;
mkdir tmp;
cd ./tmp;


pkg2appimage SAMPLE;


ARCH=x86_64 appimagetool -n ./$APP/$APP.AppDir;

cd ..;

mv /opt/bin/tmp/*AppImage /opt/bin/$APP; 
chmod a+x /opt/bin/$APP;

rm /home/$USER/.local/share/applications/$APP.desktop;
echo "LAUNCHER" >> /home/$USER/.local/share/applications/$APP.desktop;

wget https://raw.githubusercontent.com/ivan-hc/AppMan/main/applications/$APP/$APP.svg;
mv ./$APP.svg /home/$USER/.local/share/icons/;

echo "";
echo "            This AppImage is provided by";
echo "        https://github.com/AppImage/pkg2appimage ";
echo "                   'appman -i $APP' ";
echo " to install a new and more updated version, when available ";
echo "";

rm -R /opt/bin/$APP-installer /opt/bin/tmp
