#!/bin/sh

cd /opt/bin;
mkdir tmp;
cd ./tmp;


pkg2appimage ocenaudio;


ARCH=x86_64 appimagetool -n ./ocenaudio/ocenaudio.AppDir;

cd ..;

mv /opt/bin/tmp/*AppImage /opt/bin/ocenaudio; 
chmod a+x /opt/bin/ocenaudio;


echo "[Desktop Entry]
Name=ocenaudio
Name[pt]=ocenaudio
Name[de]=ocenaudio
Name[ru]=ocenaudio
GenericName=Audio Editor
GenericName[pt]=Editor de Áudio
GenericName[de]=Audio Editor
GenericName[ru]=Звуковой редактор
Comment=Edit audio files
Comment[pt]=Edite arquivos de áudio
Comment[de]=Audio Dateien bearbeiten
Comment[ru]=Редактирование звуковых файлов

Icon=ocenaudio
Type=Application
Categories=AudioVideo;Audio;AudioVideoEditing;

Exec=/opt/bin/ocenaudio %F
StartupNotify=false
Terminal=false
MimeType=application/ogg;audio/basic;audio/mpeg;audio/x-aiff;audio/x-mp3;audio/x-wav;application/x-ocenlink;x-scheme-handler/ocenaudio;" >> /home/$USER/.local/share/applications/ocenaudio.desktop;


wget https://raw.githubusercontent.com/ivan-hc/AppMan/main/applications/ocenaudio/ocenaudio.svg;
mv ./ocenaudio.svg /home/$USER/.local/share/icons/;

echo "";
echo " OcenAudio Editor is provided by https://www.ocenaudio.com ";
echo "";

rm -R /opt/bin/ocenaudio-installer /opt/bin/tmp
